### ISSUE TITLE
Stats frequency pulls.

### ISSUE THREAD

**Issue by bachulator** [syssi/xiaomi_airpurifier#10]
Home Assistant
0.54.0
Hassio 1.1

Built using Python 3

Not a bug but suggestion. The stats of the purifier are pulled way too frequently (by my estimation once 1 minute, but might be wrong since chart is too "fuzzy") which creates rather large overhead on history of HA and makes chart reading rather hard.

- Is it possible define median like algorithm which will average the value for defined number of pulls.
- Or at least not put any value in to history if the value didn't change comparing with previous one

**Comment by syssi** [comment]
Thanks for the hint. Your suggestion could apply to all sensors/components. Does the air purifier component behaves different?

**Comment by bachulator** [comment]
Most probably I could mitigate on sensor level. As far as I can tell the value pulls looks different for other my sensors.

**Comment by syssi** [comment]
Could you post a screenshot? The history of my air purifier looks like this:

![ha-history](https://user-images.githubusercontent.com/2735933/30951000-d52c765c-a420-11e7-9d08-4aae376acc43.png)

Do you use sensor templates for some attributes of the air purifier?

**Comment by bachulator** [comment]
Here you go. One from history and another as sensor.

![history](https://user-images.githubusercontent.com/28667876/30951323-f7b000d6-a42a-11e7-94b2-3bb93625e82d.jpg)

![sensor](https://user-images.githubusercontent.com/28667876/30951313-e8e0db70-a42a-11e7-86e7-4cdfbfb39a89.jpg)

**Comment by syssi** [comment]
Okay. This is normal. :-P Could you post the configuration of your "living_air_quality" sensor?

**Comment by bachulator** [comment]
It is rather simple really:
      living_air_quality:
        value_template: '{{ (states.fan.air_purifier.attributes.aqi| int) }}'
        unit_of_measurement: "nm"

**Comment by syssi** [comment]
I think this is an issue which cannot be solved here. It's more like a feature request for Home Assistant. The custom component just provides raw values of the device. You have converted the attribute to virtual sensors (template) which provides the history chart. I suggest a post processing of the raw data. In my opinion it won't be a good choice to process the data on sensor level (this component).

**Comment by bachulator** [comment]
Ok. The issue might be mitigated on sensor level. Thanks
