### ISSUE TITLE
Platform error fan.xiaomi_miio_airpurifier - cannot import name 'FanMiot' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/__init__.py)

### ISSUE THREAD

**Issue by AntoxaSa** [syssi/xiaomi_airpurifier#102]
Updated Home Asistent to 117.6 and getting this error.

**Comment by Sensei8** [comment]
Same problem. Temporary workaround - roll back to 0.6.1.

**Comment by AntoxaSa** [comment]
0.6.1 does not support heating in airfreash va4.
After installing 6.2, it works for a while, but after rebooting HA, errors like this fly out ...

**Comment by AntoxaSa** [comment]
hard reboot of Raspberry helps, before the first reboot of the Home assistant itself

**Comment by AntoxaSa** [comment]
Syssi, what could be the problem?

**Comment by Sensei8** [comment]
I removed xiaomi_airpurifier from HACS and install 0.6.2 manually and it works properly.

**Comment by AntoxaSa** [comment]
Sensei8 ,how to install manually? more details please

**Comment by Sensei8** [comment]
Need to do this steps:
1) Remove xiaomi_airpurifier from HACS
2) Download code zip from github
3) Connect to your Home Assistant via smb(i use addon Samba share)
4) Copy folder with files xiaomi_airpurifier-develop.zip\xiaomi_airpurifier-develop\custom_components\xiaomi_miio_airpurifier to \config\custom_components
5) Restart HA

**Comment by AntoxaSa** [comment]
Sensei8, version 6.2 or develop?

**Comment by Sensei8** [comment]
I used 6.2 from main github project page.

**Comment by fi-sch** [comment]
That does not work. I tried both develop branch and 6.2 release package.

**Comment by Sensei8** [comment]
In that case, need to wait for syssi answer.

**Comment by syssi** [comment]
This version bump will solve the issue: https://github.com/home-assistant/core/pull/43267

If you are able to update to the development version of HA the issue should disappear.

**Comment by AntoxaSa** [comment]
Syssi, home assistant 118 release need to wait?will it have python-miio 0.5.4?

**Comment by fi-sch** [comment]
Thanks for info! I just wanted to try your custom component because updates for Xiaomi Purifier 3H AQI attribute are really rare comparing with 2S. Anyways, it works identical with your integration so I'm sticking with built-in one for now.

**Comment by syssi** [comment]
@fi-sch In the past it was possible to change the `scan_interval` of a component to speed up the polling of the device.

**Comment by syssi** [comment]
@AntoxaSa The 0.118 release will be tomorrow. My change will be part of 0.119 (2/Dec/2020).

**Comment by syssi** [comment]
Duplicate #98.
