### ISSUE TITLE
Code -9999 UART timeout

### ISSUE THREAD

**Issue by JoeStratton** [syssi/xiaomi_airpurifier#105]
device: humidifier v1

I set the ip, name, token, and model and it throws this on startup 

```[custom_components.xiaomi_miio_airpurifier.fan] Got exception while fetching the state: {'code': -9999, 'message': 'UART timeout'}[0m```

**Comment by syssi** [comment]
Please remove the `model` and restart HA.

**Comment by syssi** [comment]
https://github.com/rytilahti/python-miio/issues/383

**Comment by syssi** [comment]
Could you provide some support here to debug the issue: https://github.com/rytilahti/python-miio/issues/606

**Comment by syssi** [comment]
Could you provide the output of:

```
# install python-miio which provides the miiocli
pip3 install python-miio

# call miiocli
miiocli airhumidifierca1 --ip IP --token TOKEN info
miiocli airhumidifierca1 --ip IP --token TOKEN status
```

**Comment by JoeStratton** [comment]
Removing the model actually worked, I had recently updated this and not sure if thats relevant but it is now resolved. thanks!

**Comment by syssi** [comment]
@JoeStratton Could you check something? Which `model` did you use in your configuration and which model is shown now as attribute at the entity list (http://hass:8124/developer-tools/state)?

**Comment by syssi** [comment]
![example](https://user-images.githubusercontent.com/2735933/99704356-93eb5080-2a98-11eb-971e-2e57ccb16ca7.png)
