### ISSUE TITLE
Dehumidifier entity is not showing current humidity

### ISSUE THREAD

**Issue by weekendjoy** [syssi/xiaomi_airpurifier#107]
![humid](https://user-images.githubusercontent.com/37536006/100091481-00e75780-2e98-11eb-9eae-46e458c5fc7e.png)

model is nwt.derh.wdh318efw1

It does not show current humidity but temperature after HASSIO current update

**Comment by syssi** [comment]
It looks like the frontend preferes the `current_temperature` over the `current_humiditiy`. If `current_temperature` is available it's used at the top right corner. I've renamed the attribute now to `_current_temperature` at the develop branch. Does this solve the issue? Do you see the current humidity again?

**Comment by weekendjoy** [comment]
It's working fine. Thanks 👍
