### ISSUE TITLE
Invalid config for [fan.xiaomi_miio]: value is not allowed 

### ISSUE THREAD

**Issue by olegskod** [syssi/xiaomi_airpurifier#108]
Good day.

When I try to connect Air Humidifier CA4 (zhimi.humidifier.ca4)
configuration.yaml:

- platform: xiaomi_miio
  name: mi.humidifier
  host: 192.168.1.27
  token: e82700fb70eca325cxxxxxxxxx9d471
  model: zhimi.humidifier.ca4

When HA check configuration file error occurs:
Invalid config for [fan.xiaomi_miio]: value is not allowed for dictionary value @ data['model']. Got 'zhimi.humidifier.ca4'. (See ?, line ?).

Integration version 0.6.2

**Comment by syssi** [comment]
If you use `xiaomi_miio` as platform you are using the official component which doesn't support the device right now. If you change the platform to `xiaomi_miio_airpurifier` this custom component is used.

**Comment by olegskod** [comment]
Thanks.
I change the platform. Now is:

Platform error fan.xiaomi_miio_airpurifier - cannot import name 'FanMiot' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/__init__.py)

**Comment by syssi** [comment]
Take a look at my last comment of #98 or downgrade the custom component to version 0.6.0.
