### ISSUE TITLE
python-miio 5.4

### ISSUE THREAD

**Issue by AntoxaSa** [syssi/xiaomi_airpurifier#118]
Good afternoon! in which version of HA will the 5.4 library be released and when?

**Comment by syssi** [comment]
![Screenshot_20201205-090849](https://user-images.githubusercontent.com/2735933/101237491-88736880-36d9-11eb-9288-f1953feba39f.png)

**Comment by AntoxaSa** [comment]
and 0.119 version will not be?

**Comment by syssi** [comment]
The next release after 0.118 will be 1.0.

**Comment by syssi** [comment]
A new HA version is released!
