### ISSUE TITLE
It's not to  work under firmware 1.2.9_61 

### ISSUE THREAD

**Issue by hugozheng2017** [syssi/xiaomi_airpurifier#12]
Model:Xiaomi Airpurifier 2
Firmware: 1.2.9_61

**Comment by tyjtyj** [comment]
My ap 2 only 1.2.4_59.

**Comment by syssi** [comment]
Please provide some more details. Did you enable the debug log? Please post your log file.

**Comment by hugozheng2017** [comment]
sorry.my problem. I got the wrong token.It run well now.
