### ISSUE TITLE
Add mjjsq04dy  support 

### ISSUE THREAD

**Issue by jackliuqinfen** [syssi/xiaomi_airpurifier#121]
Hi.
Just got my new  home and was hoping to be able to add it in Hass but i got an error.

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: mjjsq04dy

**Comment by syssi** [comment]
Could you provide the internal mode name of the device? Are you able to install python-miio and make some miiocli calls?

**Comment by lipwah** [comment]
please add mjjsq04dy support

**Comment by syssi** [comment]
Duplicate #123.
