### ISSUE TITLE
Add deerma.humidifier.jsq3 (MJJSQ04DY) support 

### ISSUE THREAD

**Issue by collinsngedu** [syssi/xiaomi_airpurifier#123]
2020-12-29 18:26:23 ERROR (MainThread) [custom_components.xiaomi_miio_airpurifier.fan] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq3

Mijia Humidifier 4L (MJJSQ04DY), 300ml/h, 25W, <=38dB

![IMG_0159](https://user-images.githubusercontent.com/63300649/103278507-9bdad080-4a06-11eb-8a00-563032926f0e.jpg)
![IMG_0162](https://user-images.githubusercontent.com/63300649/103278517-a09f8480-4a06-11eb-9320-e7c72f0ac90c.jpg)
![IMG_0161](https://user-images.githubusercontent.com/63300649/103278519-a1381b00-4a06-11eb-915a-3ec53f1234ac.PNG)
![IMG_0160](https://user-images.githubusercontent.com/63300649/103278522-a2694800-4a06-11eb-83bd-efb0da58dfc4.PNG)
![IMG_0163](https://user-images.githubusercontent.com/63300649/103278920-93cf6080-4a07-11eb-9f1e-c99e165c7a86.PNG)

**Comment by collinsngedu** [comment]
miiocli device --ip 192.168.1.80 --token xxxx info
Model: deerma.humidifier.jsq3
Hardware version: RTL8720C
Firmware version: 2.0.3

**Comment by simersim** [comment]
ERROR (MainThread) [custom_components.xiaomi_miio_airpurifier.fan] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq3

Model: deerma.humidifier.jsq3
Hardware version: RTL8720C
Firmware version: 2.0.2

**Comment by elfim-lama** [comment]
Did you manage to connect it? If so, what should be specified in the config?

**Comment by ArtFerum** [comment]
any news about this device? or have some hack how add and use in home assistant?

**Comment by egor-spk** [comment]
Any updates?

**Comment by artyom-smirnov** [comment]
Looks like support for deerma.humidifier.jsq3 can be added with minimal changes as it very similar to jsq5. I have tested it for several days and looks like all features works fine. Here diff:

```diff
diff --git a/custom_components/xiaomi_miio_airpurifier/fan.py b/custom_components/xiaomi_miio_airpurifier/fan.py
index 9fc3e47..137674b 100644
--- a/custom_components/xiaomi_miio_airpurifier/fan.py
+++ b/custom_components/xiaomi_miio_airpurifier/fan.py
@@ -137,6 +137,7 @@ MODEL_AIRHUMIDIFIER_CB2 = "zhimi.humidifier.cb2"
 MODEL_AIRHUMIDIFIER_MJJSQ = "deerma.humidifier.mjjsq"
 MODEL_AIRHUMIDIFIER_JSQ = "deerma.humidifier.jsq"
 MODEL_AIRHUMIDIFIER_JSQ1 = "deerma.humidifier.jsq1"
+MODEL_AIRHUMIDIFIER_JSQ3 = "deerma.humidifier.jsq3"
 MODEL_AIRHUMIDIFIER_JSQ5 = "deerma.humidifier.jsq5"
 MODEL_AIRHUMIDIFIER_JSQS = "deerma.humidifier.jsqs"
 MODEL_AIRHUMIDIFIER_JSQ001 = "shuii.humidifier.jsq001"
@@ -195,6 +196,7 @@ PLATFORM_SCHEMA = PLATFORM_SCHEMA.extend(
                 MODEL_AIRHUMIDIFIER_MJJSQ,
                 MODEL_AIRHUMIDIFIER_JSQ,
                 MODEL_AIRHUMIDIFIER_JSQ1,
+                MODEL_AIRHUMIDIFIER_JSQ3,
                 MODEL_AIRHUMIDIFIER_JSQ5,
                 MODEL_AIRHUMIDIFIER_JSQS,
                 MODEL_AIRHUMIDIFIER_JSQ001,
@@ -1145,6 +1147,7 @@ async def async_setup_platform(hass, config, async_add_entities, discovery_info=
         air_humidifier = AirHumidifierMjjsq(host, token, model=model)
         device = XiaomiAirHumidifierMjjsq(name, air_humidifier, model, unique_id)
     elif model in [
+        MODEL_AIRHUMIDIFIER_JSQ3,
         MODEL_AIRHUMIDIFIER_JSQ5,
         MODEL_AIRHUMIDIFIER_JSQS,
     ]:
@@ -1947,7 +1950,7 @@ class XiaomiAirHumidifierJsqs(XiaomiAirHumidifier):
         """Initialize the plug switch."""
         super().__init__(name, device, model, unique_id)
 
-        if self._model == MODEL_AIRHUMIDIFIER_JSQ5:
+        if self._model in [MODEL_AIRHUMIDIFIER_JSQ3, MODEL_AIRHUMIDIFIER_JSQ5]:
             self._device_features = FEATURE_FLAGS_AIRHUMIDIFIER_JSQ5
             self._available_attributes = AVAILABLE_ATTRIBUTES_AIRHUMIDIFIER_JSQ5
         else:
```

**Comment by syssi** [comment]
Good job! I will try to find some time tomorrow to apply your changes and prepare a release.
