### ISSUE TITLE
[Feature] Smartmi Humidifier Evaporator 2 "clean mode"

### ISSUE THREAD

**Issue by jacekpaszkowski** [syssi/xiaomi_airpurifier#124]
I've found that there is "clean mode" in Smartmi Humidifier Evaporator 2 (zhimi.humidifier.ca4, CJXJSQ04ZM).
Would it be posible to implement turning on/off this mode in this component?

**Comment by syssi** [comment]
Could you explain the clean mode?

**Comment by jacekpaszkowski** [comment]
Info from Mi Home app

![Screenshot_2020-12-29-23-43-12-078_com xiaomi smarthome](https://user-images.githubusercontent.com/4264991/103318760-baa18d00-4a2f-11eb-9527-c0bafa332bf8.jpg)
![Screenshot_2020-12-29-23-43-17-571_com xiaomi smarthome](https://user-images.githubusercontent.com/4264991/103318766-bffed780-4a2f-11eb-9c03-bea72b4b6812.jpg)
![Screenshot_2020-12-29-23-43-23-788_com xiaomi smarthome](https://user-images.githubusercontent.com/4264991/103318774-c42af500-4a2f-11eb-82d7-ab9fd06ecc17.jpg)

**Comment by syssi** [comment]
The first step to support this new feature: https://github.com/rytilahti/python-miio/pull/907
