### ISSUE TITLE
Add deerma.humidifier.jsq support

### ISSUE THREAD

**Issue by MRusinov** [syssi/xiaomi_airpurifier#125]
2021-01-02 10:10:55 INFO (MainThread) [homeassistant.components.xiaomi_miio.fan] deerma.humidifier.jsq 2.0.7 esp8266 detected
2021-01-02 10:10:55 ERROR (MainThread) [homeassistant.components.xiaomi_miio.fan] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq

![Screenshot_2021-01-02-10-23-08-638_com xiaomi smarthome](https://user-images.githubusercontent.com/15088286/103452138-89ea7d80-4ce5-11eb-9625-a0e8e21a6887.jpg)
![Screenshot_2021-01-02-10-23-50-400_com xiaomi smarthome](https://user-images.githubusercontent.com/15088286/103452141-8e169b00-4ce5-11eb-88d8-24a25a51d665.jpg)
![IMG_20210102_102659_2](https://user-images.githubusercontent.com/15088286/103452142-9078f500-4ce5-11eb-8e04-067c89822f93.jpg)

**Comment by MRusinov** [comment]
# miiocli airhumidifiermjjsq --ip 192.168.xxx.xxx --token xxxxxxxxxxxxxxxxxxxxxxxxxx status
Power: on
Mode: OperationMode.Humidity
Temperature: 21 °C
Humidity: 51 %
LED: True
Buzzer: True
Target humidity: 55 %
No water: False
Water tank detached: False
Wet protection: None

**Comment by MRusinov** [comment]
https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq:1

{"type":"urn:miot-spec-v2:device:humidifier:0000A00E:deerma-jsq:1","description":"Humidifier","services":[{"iid":1,"type":"urn:miot-spec-v2:service:device-information:00007801:deerma-jsq:1","description":"Device Information","properties":[{"iid":1,"type":"urn:miot-spec-v2:property:manufacturer:00000001:deerma-jsq:1","description":"Device Manufacturer","format":"string","access":["read"]},{"iid":2,"type":"urn:miot-spec-v2:property:model:00000002:deerma-jsq:1","description":"Device Model","format":"string","access":["read"]},{"iid":3,"type":"urn:miot-spec-v2:property:serial-number:00000003:deerma-jsq:1","description":"Device Serial Number","format":"string","access":["read"]},{"iid":4,"type":"urn:miot-spec-v2:property:firmware-revision:00000005:deerma-jsq:1","description":"Current Firmware Version","format":"string","access":["read"]}]},{"iid":2,"type":"urn:miot-spec-v2:service:humidifier:00007818:deerma-jsq:1","description":"Humidifier","properties":[{"iid":1,"type":"urn:miot-spec-v2:property:on:00000006:deerma-jsq:1","description":"Switch Status","format":"bool","access":["read","write","notify"]}]},{"iid":3,"type":"urn:miot-spec-v2:service:environment:0000780A:deerma-jsq:1","description":"Environment","properties":[{"iid":1,"type":"urn:miot-spec-v2:property:relative-humidity:0000000C:deerma-jsq:1","description":"Relative Humidity","format":"uint8","access":["read","notify"],"unit":"percentage","value-range":[0,90,1]},{"iid":2,"type":"urn:miot-spec-v2:property:temperature:00000020:deerma-jsq:1","description":"Temperature","format":"float","access":["read","notify"],"unit":"celsius","value-range":[-10,60,1]}]},{"iid":4,"type":"urn:miot-spec-v2:service:indicator-light:00007803:deerma-jsq:1","description":"Indicator Light","properties":[{"iid":1,"type":"urn:miot-spec-v2:property:on:00000006:deerma-jsq:1","description":"Switch Status","format":"bool","access":["read","write","notify"]}]},{"iid":5,"type":"urn:miot-spec-v2:service:alarm:00007804:deerma-jsq:1","description":"Alarm","properties":[{"iid":1,"type":"urn:miot-spec-v2:property:alarm:00000012:deerma-jsq:1","description":"Alarm","format":"bool","access":["read","write","notify"]}]}]}

**Comment by syssi** [comment]
The official component in HA doesn't support the device. If you use this custom component the device is already supported. Just give it a try.

**Comment by MRusinov** [comment]
Oh, thank you! I've added it, and now it works!

**Comment by dave-castle** [comment]
Would you mind working with the developers of HA to include it with the integration via cloud, cause I think that’s the only way to support vlan/subnets, right?
