### ISSUE TITLE
zhimi.humidifier.ca4 not attribute child lock bug?

### ISSUE THREAD

**Issue by AntoxaSa** [syssi/xiaomi_airpurifier#128]
zhimi.humidifier.ca4 not attribute child lock bug?
![not attribute](https://user-images.githubusercontent.com/71827946/104021767-2a0e3e00-51e1-11eb-925a-96864def3109.jpg)

**Comment by syssi** [comment]
Which version of the component do you use? This custom component should support the `child_lock` property.

**Comment by syssi** [comment]
At the official HA component the property is missing:

https://github.com/home-assistant/core/blob/dev/homeassistant/components/xiaomi_miio/fan.py#L341

**Comment by AntoxaSa** [comment]
xiaomi_airpurifier 6.2
I tried to use python-miio 5.4 directly but there are other problems, wrong humidifier modes: Auto/Mid/low/hight

**Comment by syssi** [comment]
Could you provide your configuration? Are you sure you are using `xiaomi_miio_airpurifier` instead of `xiaomi_miio`?

**Comment by AntoxaSa** [comment]
- platform: xiaomi_miio_airpurifier
    name: Xiaomi Air Humidifier
    host: 192.168.1.84
    token: my token
    model: zhimi.humidifier.ca4

**Comment by syssi** [comment]
And there is still no `child_lock` property?

**Comment by AntoxaSa** [comment]
not (
Home Assistant 2021.1.0

**Comment by AntoxaSa** [comment]
![IMG_1977](https://user-images.githubusercontent.com/71827946/104130486-d04d7580-5392-11eb-812d-629257b7fb0b.jpg)

**Comment by syssi** [comment]
I've released v0.6.3. The issue should be fixed now. Please update and give it a try. ß

**Comment by AntoxaSa** [comment]
Thank you! everything is working
