### ISSUE TITLE
zhimi.humidifier.ca4 set fan speed

### ISSUE THREAD

**Issue by alesoft73** [syssi/xiaomi_airpurifier#129]
Dear.
For zhimi.humidifier.ca4 don't work service:

      service: fan.set_speed
      data:
        entity_id: fan.xiaomi_air_purifier
        speed: '{{ states.input_select.airpurifier_mode.state }}'

speed_list: Auto, Low, Mid, High in the attribute.
I use custom component xiaomi_miio_airpurifier.

Many thanks.

**Comment by syssi** [comment]
Do you see any error message? Could you provide the configuration of your input_select?

**Comment by alesoft73** [comment]
> Do you see any error message? Could you provide the configuration of your input_select?

This is a input select....

input_select:
  humidifies_fan_speed_select:
    name: Selezione Aspirazione
    options:
      - Auto
      - Low
      - Mid
      - High


This is a service i use ..

            - service: fan.set_speed
              data:
                entity_id: fan.xiaomi_air_humidifier
                speed: Auto 

Nothing error in the log.
Would you to active a debug log  ??

**Comment by alesoft73** [comment]
I have resolve..
The problem is the fan is "on" for change the state. 
Many thanks!

**Comment by syssi** [comment]
So you have to turn on the device first? Afterwards set_speed is working? If the device is turned off using `set_speed` to turn the device on doesn't work?

**Comment by alesoft73** [comment]
Yes.... exactly..

**Comment by alesoft73** [comment]
> 
> 
> So you have to turn on the device first? Afterwards set_speed is working? If the device is turned off using `set_speed` to turn the device on doesn't work?

Yes.... exactly..
I have rounded the problem with service to start fan on and after start service for change velocity.

**Comment by syssi** [comment]
I'm closing this issue. If you don't like the behaviour please open an issue here: https://github.com/rytilahti/python-miio

It's the underlying library which implement the device handling.
