### ISSUE TITLE
zhimi.humidifier.ca4 is missing attribute use_time

### ISSUE THREAD

**Issue by dvino** [syssi/xiaomi_airpurifier#130]
**zhimi.humidifier.ca4** 

At my installation of custom component I include follow line inside [fan.py](https://github.com/syssi/xiaomi_airpurifier/blob/1cd406664b40b24fc00b8a74cc8b83d6d047e720/custom_components/xiaomi_miio_airpurifier/fan.py#L442)

    ATTR_USE_TIME: "use_time",

It work OK for me

![himidifier](https://user-images.githubusercontent.com/20031784/104690181-06815100-5715-11eb-8ed7-77689c58d84e.jpg)

**Comment by syssi** [comment]
Do you like to provide an pull request?
