### ISSUE TITLE
Help needed to setup my zhimi.humidifier.cb1

### ISSUE THREAD

**Issue by shopmen99** [syssi/xiaomi_airpurifier#135]
Xiaomi Miio Device
of the device is listed, however, it does not find any data.
only the fan is displayed

**Comment by syssi** [comment]
Adding @robi59italy because he asked the same question yesterday.

**Comment by syssi** [comment]
Please goto http://homeassistant-ip:homeasstiant-port/developer-tools/state und provide a screenshot of your `fan` entity. All values/data are embedded into this entity as attributes. If you want a sensor entity per attribute you've to setup template sensors:

https://github.com/syssi/xiaomi_airpurifier#template-sensor-example

**Comment by shopmen99** [comment]
do I have to create all entries myself?
like: 
model
temperature
humidity
mode
buzzer
child_lock

![image](https://user-images.githubusercontent.com/77403745/104913375-cd074a80-598d-11eb-8b32-aaf45db1c93c.png)

**Comment by robi59italy** [comment]
> do I have to create all entries myself?
> like:
> model
> temperature
> humidity
> mode
> buzzer
> child_lock
> 
> ![image](https://user-images.githubusercontent.com/77403745/104913375-cd074a80-598d-11eb-8b32-aaf45db1c93c.png)

I can answer because I just made.. yes... like this:

in sensors.yaml

 - platform: template
    sensors:
      airhumidifier_temperature:
        friendly_name: Air Humidifier Temperature
        value_template: '{{ states.fan.Xiaomi_Miio_Device.attributes.temperature }}'
        unit_of_measurement: '°C'
      airhumidifier_humidity:
        friendly_name: Air Humidifier Humidity
        value_template: '{{ states.fan.Xiaomi_Miio_Device.attributes.humidity }}'
        unit_of_measurement: '%'
        icon_template: mdi:water-percent
      airhumidifier_depth:
        friendly_name: Livello acqua
        value_template: '{{ states.fan.Xiaomi_Miio_Device.attributes.depth }}'
        unit_of_measurement: '%'
        icon_template: mdi:water-percent

I just started and I have to insert the other one

**Comment by syssi** [comment]
Correct. The custom component provides a single fan entity at the moment. This will change some day. For now you have to setup additional entities on your own via templates.

**Comment by shopmen99** [comment]
Thanks for the info
sorry the whole thing is new to me.
I do not understand why I have the status: unavailable
get?

I'm a bit lost at the moment.
do not have much experience with the setup.
currently use only ready integrations.

if I have understood correctly, the infromations must all in the:  configuration.yaml?

**Comment by syssi** [comment]
If your device is unavailable something is wrong. Probably the token. It must look like this:

![screenshot](https://user-images.githubusercontent.com/2735933/104922050-75231080-599a-11eb-8ead-b0ec7ac638ea.jpg)

**Comment by robi59italy** [comment]
> Thanks for the info
> sorry the whole thing is new to me.
> I do not understand why I have the status: unavailable
> get?
> fan:
> 
> * platform: xiaomi_miio_airpurifier
>   model: zhimi.humidifier.cb1
>   host: 192.168.1.99
>   token: %%%%%%%%%%%%%%%%%%%%%%%%%%%%

> sensors:
> 
> * platform: template
>   sensors:
>   airhumidifier_temperature:
>   friendly_name: Air Humidifier Temperature
>   value_template: '{{ states.fan.Xiaomi_Miio_Device.attributes.temperature }}'
>   unit_of_measurement: '°C'
>   airhumidifier_humidity:
>   friendly_name: Air Humidifier Humidity
>   value_template: '{{ states.fan.Xiaomi_Miio_Device.attributes.humidity }}'
>   unit_of_measurement: '%'
>   icon_template: mdi:water-percent
>   airhumidifier_depth:
>   friendly_name: Livello acqua
>   value_template: '{{ states.fan.Xiaomi_Miio_Device.attributes.depth }}'
>   unit_of_measurement: '%'
>   icon_template: mdi:water-percent

**Comment by robi59italy** [comment]
> Thanks for the info
> sorry the whole thing is new to me.
> I do not understand why I have the status: unavailable
> get?
> 
> I'm a bit lost at the moment.
> do not have much experience with the setup.
> currently use only ready integrations.
> 
> if I have understood correctly, the infromations must all in the: configuration.yaml?
> 
> Like this:
> fan:
> 
> * platform: xiaomi_miio_airpurifier
>   model: zhimi.humidifier.cb1
>   host: 192.168.1.99
>   token: %%%%%%%%%%%%%%%%%%%%%%%%%%%%

Yes and after restart home assistant (after checking if configuration validation is ok)
After restart go in configuration-> entities and search "xia" you should have to see it
Otherwyse there is a problem with IP or token

**Comment by shopmen99** [comment]
thanks now it works. was an error in the IP.

Where exactly do I have to enter the sensors and the switch so that I get more options?

**Comment by robi59italy** [comment]
> thanks now it works. was an error in the IP.
> 
> Where exactly do I have to enter the sensors and the switch so that I get more options?

sensors
you have to options.. you can write on the configuration.yaml or..
write this in the configuration.yaml   --->  sensor: !include /config/sensors.yaml
create an empty file in the config directory called sensors.yaml
and write all in the sensors.all

I prefer this option so all it's more clear

Switch
You can do the same, write in configuration.yaml or create a switch.yaml file (but write the link switch:!include /config/switch.yaml in the configuration.yaml

**Comment by syssi** [comment]
If you like it super-clean you could bundle it to a package: https://www.home-assistant.io/docs/configuration/packages/

**Comment by shopmen99** [comment]
thanks for the super help. now everything goes wonderfully.
