### ISSUE TITLE
dmaker.p9: Support oscillation angle of 150 degrees instead of 140

### ISSUE THREAD

**Issue by maximatchev** [syssi/xiaomi_airpurifier#139]
**xiaomi_miio_airpurifier.fan_set_oscillation_angle**
Angle 150 degrees must be available for dmaker.p9 (it's available in MiHome)

**fan.set_direction**
Doesn't work for dmaker.p9

I haven;t found how can I turn on/off **notification sound** and **indicator light**

**Comment by syssi** [comment]
TODOs:

- [ ] Allow 150 degrees as oscillation angle of the p9
- [ ] It's possible to control the notification sound? (`set_buzzer` support)
- [ ] It's possible to control the indicator light? (`set_led` support)

**Comment by syssi** [comment]
Did you try to use `set_buzzer` to turn the notification sound on/off and please try `set_led` to control the indicator light. Does it work?
