### ISSUE TITLE
Add zhimi.humidifier.cb2 support

### ISSUE THREAD

**Issue by youngbin126** [syssi/xiaomi_airpurifier#140]
I think it's almost identical to cb1. 
syssi already reviewed as below, and I wish it is reflected on HACS version too.

https://github.com/rytilahti/python-miio/pull/917

Thank you

**Comment by syssi** [comment]
Could you provide some details about the device to extend the list of supported devices in future: https://github.com/syssi/xiaomi_airpurifier#supported-devices

**Comment by youngbin126** [comment]
Name | Smartmi Evaporative Humidifier (Korea Version) 
Model | zhimi.humidifier.cb2 
Model no. | CJXJSQ02ZM(?)
Specs | 8W, 240x240x363mm

I wish this information help you.

**Comment by syssi** [comment]
The device support is available in python-miio. It should be easy to add the device here.

**Comment by syssi** [comment]
@youngbin126 Could you provide a photo of the device type label and the top of the device. There should be a SKV6001 sticker or something.
