### ISSUE TITLE
Implement new fan model to use presets

### ISSUE THREAD

**Issue by syssi** [syssi/xiaomi_airpurifier#143]
cp. https://github.com/syssi/xiaomi_fan/issues/99

**Comment by bdraco** [comment]
Here is an example of one I updated that works with the old and new model

https://github.com/shbatm/hacs-isy994/pull/78

**Comment by tannisroot** [comment]
The air purifiers have a slider in the app that controls the intensity of airflow in manual mode, could the % slider in core-21.03 be used for that? Although it won't be functional in Auto and Silent modes.

**Comment by syssi** [comment]
Done: https://github.com/syssi/xiaomi_airpurifier/commit/900dc87aae3fe3f1e0b9bcedd51d9c436cc2c231
