### ISSUE TITLE
Help with MJJSQ04DY 

### ISSUE THREAD

**Issue by areyoufserious** [syssi/xiaomi_airpurifier#151]
I'm owner of MJJSQ04DY. How can i help?

**Comment by elfim-lama** [comment]
Did you manage to connect it? If so, what should be specified in the config?

**Comment by elfim-lama** [comment]
> I'm owner of MJJSQ04DY. How can i help?
Help to connect?

**Comment by syssi** [comment]
Anybody here to provide some testing to get this device supported?

**Comment by syssi** [comment]
Duplicate of #158.
