### ISSUE TITLE
Support Smart Mi Humidifer MJJSQ04DY (deerma.humidifier.jsq3)

### ISSUE THREAD

**Issue by RainCat1998** [syssi/xiaomi_airpurifier#158]
I'm owner of MJJSQ04DY.  How can I help to support this device?

**Comment by Xaxolhd** [comment]
deerma.humidifier.jsq3 я владелец, что нужно для поддержки приложения

**Comment by syssi** [comment]
Anybody here to provide some testing to get this device supported?

**Comment by syssi** [comment]
Duplicate of #123.
