### ISSUE TITLE
Speed field was change  for zhimi.airfresh.va4.

### ISSUE THREAD

**Issue by wisesokol** [syssi/xiaomi_airpurifier#160]
Hi.
UI of zhimi.airfresh.va4 had change.
VA4 model have 5 modes  for fan speed. It's interval, silent, low, middle, strong. Now i have other interface for manage it. It's not correct.
![изображение](https://user-images.githubusercontent.com/48487551/113480508-341ca180-949d-11eb-839e-e8b036774c59.png)

Early i had 5 modes in speed field.

**Comment by syssi** [comment]
Are you sure you are using this custom component?

**Comment by wisesokol** [comment]
fan:
  - platform: xiaomi_miio_airpurifier
    name: xiaomi_miio_device
    host: 192.168.1.78
    token: deab99d2f17c06xxxxxxxxxxxxxx
    model: zhimi.airfresh.va4 

![изображение](https://user-images.githubusercontent.com/48487551/113484181-a0080580-94af-11eb-8fd1-3efcf153d0e8.png)

 
In node red work fine. In call service work fine too.

Only in UI i see this problem. 

Maybe Home assistent was changed in core-2021.3.2.
I will now upgrade to core-2021.3.4 and check.

**Comment by wisesokol** [comment]
After update i have same problem.

**Comment by syssi** [comment]
Got it. I will care about a fix but it will take some time.

**Comment by foreignerby** [comment]
Hi @syssi ,

I think, that my issue at #131 may be related to this too.
[Here](https://github.com/syssi/xiaomi_airpurifier/issues/131#issuecomment-808891856)

**Comment by syssi** [comment]
Fixed by https://github.com/syssi/xiaomi_airpurifier/commit/900dc87aae3fe3f1e0b9bcedd51d9c436cc2c231.

Please test again as soon as version 0.6.5 is released.

**Comment by wisesokol** [comment]
it works! Thanks.
![изображение](https://user-images.githubusercontent.com/48487551/114504173-21416400-9c37-11eb-9e3e-32d5cf640159.png)
