### ISSUE TITLE
Status response of the dmaker.fan.p9 cannot be handled

### ISSUE THREAD

**Issue by biscuitee** [syssi/xiaomi_airpurifier#164]
Hi, updated the Home Assistant to 2021.4.1 and the xiaomi_airpurifier integration broke.   HA can't link to xiaomi tower fan dmaker.fan.p9 with xiaomi_airpurfier integration.  Can someone help?

**Comment by maximatchev** [comment]
same problem with dmaker.p9 too ((

**Comment by JeroLajHub** [comment]
I confirm the diagnostic.

**Comment by syssi** [comment]
I would be happy about some details about the issue. Do you see anything at your logs?

**Comment by maximatchev** [comment]
Уровень: ОШИБКА
Logger: homeassistant.components.fan
Source: custom_components/xiaomi_miio_airpurifier/fan.py:2405
Integration: Вентилятор (documentation, issues)
First occurred: 18:10:13 (1 occurrences)
Last logged: 18:10:13

xiaomi_miio_airpurifier: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 482, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 2405, in async_update
    self._natural_mode = state.mode == FanOperationMode.Nature
  File "/usr/local/lib/python3.8/site-packages/miio/fan_miot.py", line 106, in mode
    return OperationMode[OperationModeMiot(self.data["mode"]).name]
  File "/usr/local/lib/python3.8/enum.py", line 339, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 662, in __new__
    raise ve_exc
ValueError: None is not a valid OperationModeMiot

**Comment by syssi** [comment]
Which device model do you own (dmaker.fan.p5)?

**Comment by maximatchev** [comment]
> dmaker.fan.p5

dmaker.fan.p9

**Comment by syssi** [comment]
Could you increase the log level of python-miio at your configuration.yaml:

```
# configuration.yaml
logger:
  default: warn
  logs:
    miio: debug
```

I would like to see the `get_properties` request and the `response` of the device. Because it looks like the retrieved `operation_mode` is `None` which should be impossible (valid values are 0 (Normal) and 1 (Natural)).

**Comment by maximatchev** [comment]
homeassistant.log

https://drive.google.com/file/d/1oMa_IT4nBMrtxA2VJrXUiLN8vHZmun_y/view?usp=sharing

**Comment by syssi** [comment]
It looks like your device has a bad day:

```
<< {'id': 1, 'result': {'life': 30316, 'uid': 1730285405, 'model': 'dmaker.fan.p9', 'token': 'ffff', 'ipflag': 1, 'fw_ver': '2.1.3', 'mcu_fw_ver': '0003', 'miio_ver': '0.0.9', 'hw_ver': 'esp8266', 'mmfree': 21876, 'mac': '44:FF:FF:FF:FF:FF', 'wifi_fw_ver': '8903c22', 'ap': {'ssid': 'XXXXXXXXXXXXXXX', 'bssid': '50:FF:FF:FF:FF:FF', 'rssi': -50, 'primary': 9}, 'netif': {'localIp': '192.168.1.192', 'mask': '255.255.255.0', 'gw': '192.168.1.1'}}, 'exe_time': 40}

# Request:
>>: {'id': 1, 'method': 'get_properties', 'params': [{'did': 'power', 'siid': 2, 'piid': 1}, {'did': 'fan_level', 'siid': 2, 'piid': 2}, {'did': 'child_lock', 'siid': 3, 'piid': 1}, {'did': 'fan_speed', 'siid': 2, 'piid': 10}, {'did': 'swing_mode', 'siid': 2, 'piid': 4}, {'did': 'swing_mode_angle', 'siid': 2, 'piid': 5}, {'did': 'power_off_time', 'siid': 2, 'piid': 6}, {'did': 'buzzer', 'siid': 2, 'piid': 8}, {'did': 'light', 'siid': 2, 'piid': 7}, {'did': 'mode', 'siid': 2, 'piid': 3}, {'did': 'set_move', 'siid': 2, 'piid': 9}]}

# Response:
<< {'id': 1, 'result': [
  {'did': 'power', 'siid': 2, 'piid': 1, 'code': 0, 'value': False},
  {'did': 'fan_level', 'siid': 2, 'piid': 2, 'code': 0, 'value': 4},
  {'did': 'child_lock', 'siid': 3, 'piid': 1, 'code': 0, 'value': False},
  {'did': 'fan_speed', 'siid': 2, 'piid': 10, 'code': -4003},
  {'did': 'swing_mode', 'siid': 2, 'piid': 4, 'code': 0, 'value': 1},
  {'did': 'swing_mode_angle', 'siid': 2, 'piid': 5, 'code': 0, 'value': True},
  {'did': 'power_off_time', 'siid': 2, 'piid': 6, 'code': 0, 'value': 120},
  {'did': 'buzzer', 'siid': 2, 'piid': 8, 'code': 0, 'value': 0},
  {'did': 'light', 'siid': 2, 'piid': 7, 'code': 0, 'value': True},
  {'did': 'mode', 'siid': 2, 'piid': 3, 'code': -4003},
  {'did': 'set_move', 'siid': 2, 'piid': 9, 'code': 0, 'value': True}],
  'exe_time': 220
}
```

The properties `mode` and `fan_speed` are returning strange values (`-4003`). I will try to investigate what's going on here.

**Comment by syssi** [comment]
Could you turn the device `on` and provide another log? May be `fan_speed` and `mode` cannot be provided if the device is turned off.

**Comment by maximatchev** [comment]
new log. HomeAssistant started when fan was on

https://drive.google.com/file/d/1oMa_IT4nBMrtxA2VJrXUiLN8vHZmun_y/view?usp=sharing

**Comment by syssi** [comment]
```
# Response
<< {'id': 1, 'result': [
  {'did': 'power', 'siid': 2, 'piid': 1, 'code': 0, 'value': True},
  {'did': 'fan_level', 'siid': 2, 'piid': 2, 'code': 0, 'value': 4},
  {'did': 'child_lock', 'siid': 3, 'piid': 1, 'code': 0, 'value': False},
  {'did': 'fan_speed', 'siid': 2, 'piid': 10, 'code': -4003},
  {'did': 'swing_mode', 'siid': 2, 'piid': 4, 'code': 0, 'value': 0},
  {'did': 'swing_mode_angle', 'siid': 2, 'piid': 5, 'code': 0, 'value': True},
  {'did': 'power_off_time', 'siid': 2, 'piid': 6, 'code': 0, 'value': 120},
  {'did': 'buzzer', 'siid': 2, 'piid': 8, 'code': 0, 'value': 0},
  {'did': 'light', 'siid': 2, 'piid': 7, 'code': 0, 'value': True},
  {'did': 'mode', 'siid': 2, 'piid': 3, 'code': -4003},
  {'did': 'set_move', 'siid': 2, 'piid': 9, 'code': 0, 'value': True}],
  'exe_time': 200
}
```

The device is turned on but `mode` and `fan_speed` are still broken. Did you update the device firmware recently?

**Comment by maximatchev** [comment]
I think, it was updated something about 2 months ago... But I'm not sure...
It's 2.1.3.0003 version. The latest

**Comment by G1K** [comment]
`ValueError: None is not a valid OperationModeMiot`
I have the same error

fan firmware 2.1.3.0003

**Comment by syssi** [comment]
@G1K Could you check the response of your device, too?

**Comment by syssi** [comment]
@rytilahti Could you have a quick look into this? It looks like the `dmaker.fan.p9` was supported properly with version `0.6.4` (`python-miio==0.5.3`). Since `python-miio>=0.5.5` in `0.6.5` the property `mode` and `fan_speed` returns the value `-4003`. This cannot be a conversion/casting/typing issue at `python-miio`, right?

My next step is to lookup the miot specs. It's possible the specs has changed with the latest firmware update and `siid` and/or `piid` has changed.

**Comment by syssi** [comment]
The specs haven't changed. It's still version 1: https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:fan:0000A005:dmaker-p9:1

**Comment by syssi** [comment]
Specs used at the request:

```
>>: {'id': 1, 'method': 'get_properties', 'params': [
  {'did': 'power', 'siid': 2, 'piid': 1},
  {'did': 'fan_level', 'siid': 2, 'piid': 2},
  {'did': 'child_lock', 'siid': 3, 'piid': 1},
  {'did': 'fan_speed', 'siid': 2, 'piid': 10},
  {'did': 'swing_mode', 'siid': 2, 'piid': 4},
  {'did': 'swing_mode_angle', 'siid': 2, 'piid': 5},
  {'did': 'power_off_time', 'siid': 2, 'piid': 6},
  {'did': 'buzzer', 'siid': 2, 'piid': 8},
  {'did': 'light', 'siid': 2, 'piid': 7},
  {'did': 'mode', 'siid': 2, 'piid': 3},
  {'did': 'set_move', 'siid': 2, 'piid': 9}
]}
```

**Comment by syssi** [comment]
I found the issue. The use specs aren't selected properly. `piid=3` is in use for `mode` and `piid=10` to retrieve the `fan_speed`. Should be `4` and `11`.
