### ISSUE TITLE
Error after module update

### ISSUE THREAD

**Issue by prokazzzzza** [syssi/xiaomi_airpurifier#172]
Platform error fan.xiaomi_miio_airpurifier - cannot import name 'AirFreshA1' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/__init__.py)

**Comment by prokazzzzza** [comment]
Versions above 0.6.4 cause the current error.

**Comment by syssi** [comment]
Which Home Assistant Core version do you use? Please provide a list of all custom components you are using. The manifest.json of all `python-miio` requiring custom components must point to the same version. It looks like you are using an outdated version.

**Comment by darkleliel** [comment]
> Which Home Assistant Core version do you use? Please provide a list of all custom components you are using. The manifest.json of all `python-miio` requiring custom components must point to the same version. It looks like you are using an outdated version.

same issue
Home Assistant: core-2021.4.5
xiaomi_miio_airpurifier: 0.6.6

**Comment by syssi** [comment]
Do you use additional custom components interfacing Xiaomi devices? Please provide a list of your custom components.

**Comment by syssi** [comment]
cp. https://github.com/syssi/xiaomi_airpurifier/issues/167

**Comment by darkleliel** [comment]
> Do you use additional custom components interfacing Xiaomi devices? Please provide a list of your custom components.

list of components with xiaomi
Xiaomi Gateway (Aqara)   (because offcial xiaomi_miio gateway document says "Not yet implemented features: Gateway ringtones/sounds")
xiaomi_miio    (official, vacuum/IR remote)
Yeelight   (official)
xiaomi_airconditioningcompanion   (HACS, 0.2.2)
xiaomi_airpurifier    (HACS)(0.6.4 works fine. 0.6.6 can not work with deerma.humidifier.jsq1, both zhimi.humidifier.v1 and zhimi.airpurifier.sa2 seems been officially support by xiaomi_miio)

**Comment by syssi** [comment]
@darkleliel Please check the manifest.json of very custom component. If `python-miio` is mentioned as requirement you have to bump to version to `0.5.5`. One component downgrades the python-miio library at the moment.

**Comment by prokazzzzza** [comment]
Thank you.  Yes, I had an outdated Home Assistant kernel. Now it's working after updating the kernel.

**Comment by syssi** [comment]
You are right. 0.6.6 requires one of the most recent HA core release. Sorry for the trouble. I will try to add a minimum required version constraint in future.
