### ISSUE TITLE
Humidifier model : zhimi.humidifier.ca4 fan mode speed don't work

### ISSUE THREAD

**Issue by alesoft73** [syssi/xiaomi_airpurifier#173]
Speeds are selectable but do not work.
In version 0.6.6 the list of speeds is:
low  medium high 

![0 6 6](https://user-images.githubusercontent.com/46445679/114877742-dde62180-9dff-11eb-8208-1642860c669d.JPG)

In your old version instead the speeds are:
Auto, Low, Mid, High
and everything works correctly.

![0 6 3](https://user-images.githubusercontent.com/46445679/114877975-138b0a80-9e00-11eb-918f-5dd91917aad3.jpg)

Many thakns

**Comment by syssi** [comment]
Do you use this custom component or the official version?

**Comment by alesoft73** [comment]
I use your custom component.. and confirm with version 0.6.4 now return to work perfect.

**Comment by suarezcp87** [comment]
Hello, try too use service: fan.set_preset_mode

**Comment by syssi** [comment]
The strange thing is there are no `preset_modes` available at the attributes. The `speed` and `speed_list` was removed in 0.6.6 so they shouldn't be there if this custom component is in use.

**Comment by syssi** [comment]
This is how it should look like:

![ha1](https://user-images.githubusercontent.com/2735933/115067832-ba9b9f00-9ef1-11eb-8fc0-04553c4114a2.png)
![ha2](https://user-images.githubusercontent.com/2735933/115067840-bd968f80-9ef1-11eb-9cda-fcb93ad4b224.png)

**Comment by suarezcp87** [comment]
I have like this
![1](https://user-images.githubusercontent.com/78756329/115074259-2259e600-9f02-11eb-9eba-95e61269d8dc.jpg)
![2](https://user-images.githubusercontent.com/78756329/115074260-22f27c80-9f02-11eb-80f9-026df2a3b4cf.jpg)

**Comment by syssi** [comment]
@suarezcp87 Perfect! This is version 0.6.6. The screenshot of @alesoft73 isn't version 0.6.6.

**Comment by alesoft73** [comment]
Now i have installed ultimate version:

<img width="852" alt="Schermata 2021-04-18 alle 23 20 54" src="https://user-images.githubusercontent.com/46445679/115161236-cd060c00-a09c-11eb-8684-5a677d4ed14d.png">


Preset mode work if i select form entity_id, but don't work with service

service: fan.preset_mode
data:
  entity_id: fan.xiaomi_air_purifier
  preset_mode: Auto

don't set...
Many thanks

**Comment by syssi** [comment]
The service is called `fan.set_preset_mode`.
