### ISSUE TITLE
 Xiaomi Mijia Smart 1X Fan : speed levels and percentage can't be controlled..

### ISSUE THREAD

**Issue by keshabit** [syssi/xiaomi_airpurifier#174]
# Xiaomi Mijia Smart 1X Fan
fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Smart Fan
    host: ipipip
    token: xxx    
    model: dmaker.fan.p5 

I can on off fan but can't control the different speed level or percentage! Shows following error..
"Failed to call service fan/set_percentage. 'FanP5' object has no attribute 'set direct speed'"

I can use same features flawlessly using the Xiaomi Mi app...

**Comment by syssi** [comment]
Fixed in 0.6.7. Please give it a try!

**Comment by keshabit** [comment]
It's working! Thanks a lot.
