### ISSUE TITLE
Add zhimi.fan.za5 (Smartmi Standing Fan 3) support

### ISSUE THREAD

**Issue by teajay-git-hub** [syssi/xiaomi_airpurifier#180]
Code is zhimi.fan.za5

**Comment by syssi** [comment]
Cross link: https://github.com/syssi/xiaomi_fan/issues/69

**Comment by syssi** [comment]
The ZA5 is supported by the custom component `xiaomi_fan` now: https://github.com/syssi/xiaomi_fan

Please give it a try!
