### ISSUE TITLE
zhimi.humidifier.ca4: water_level is unavailable

### ISSUE THREAD

**Issue by kubiner** [syssi/xiaomi_airpurifier#182]
value_template: "{{  states.fan.hum_spl.attributes.water_level }}" 
даёт пусто  (value_template: "" )
другие атрибуты : влажность, температура, скорость и т.д - работают

**Comment by vsimanin** [comment]
Такая же проблема на .ca1
Вот нашел решение https://github.com/home-assistant/core/issues/44292

**Comment by syssi** [comment]
This is an issue of the official component. If you use this custom component the `water_leve` attribute is available.

**Comment by syssi** [comment]
It looks like the issue is solved.
