### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by akarpych** [syssi/xiaomi_airpurifier#184]
Platform error fan.xiaomi_miio_airpurifier - cannot import name 'Fan1C' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/__init__.py) Platform error fan.xiaomi_miio_airpurifier - cannot import name 'Fan1C' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/__init__.py)

**Comment by akarpych** [comment]
After update...

**Comment by syssi** [comment]
Which HA version do you use? Do you have additional custom components installed interfacing xiaomi devices? Please make sure every manifest.json is requiring the same python-miio version. Version `0.5.6` and HA core `2021.5.1` is required.

**Comment by akarpych** [comment]
Ok! Thanks!
