### ISSUE TITLE
zhimi.airpurifier.mc1 doesn't work anymore

### ISSUE THREAD

**Issue by jokerigno** [syssi/xiaomi_airpurifier#188]
With latest HA update 2021.05 air purifier doesn't work anymore.

Old discovered device is unavailable and a new one is discovered but as soon as it is added to config it is unavailable too.

**Comment by syssi** [comment]
Do you use this custom component or the official one? Please update this custom component and make sure every custom component interfacing a Xiaomi device / using `python-miio` is pointing to the same version (`0.5.6`) at the `manifest.json`.

**Comment by jokerigno** [comment]
"Do you use this custom component or the official one?" Good question. I think I use custom because I installed 0.6.11 of your "Xiaomi Mi Air Purifier, Air Humidifier, Air Fresh and Pedestal Fan Integration". I also see in HACS that I use 1.4.4 of "Xiaomi Philips Lights Integration" that I use for my bed side lamps (Don't know if gateway is managed by custom component). What I noticed is that light integration has in manifest.json "python-miio>=0.5.3". Maybe you need to upgrade it too?

**Comment by syssi** [comment]
Most of the time the problem is the library `python-miio` gets downgraded because a manifest enforces an outdated version `==0.5.3`. By `>=` I'm trying to express the custom component is happy with any version above `0.5.3`. But it's possible the `>=` operator doesn't work as intended. Do you see any error messages at your homeassistant.log?

**Comment by syssi** [comment]
Please provide all sections of your `configuration.yaml` interfacing Xiaomi devices. This custom component doesn't support config flow right now. If you are using this custom component there must be a `platform: xiaomi_miio_airpurifier` section.

**Comment by jokerigno** [comment]
This is the config:

fan:
  # Xiaomi Air Purifier 2S
  - platform: xiaomi_miio
    host: 192.168.2.60
    token: f48b728634eedxxxxxxxxxx1a13ef8ebf646
    name: Purificatore Aria

Basically discover found it by IP adress (192.168.2.60) and asks me for token but when I add it it becomes unavailable .

**Comment by syssi** [comment]
This is the official component.

**Comment by jokerigno** [comment]
Ok I removed it and reboot. Now discover don't find anything. Device seems offline....let me try with "official" xiaomi app or try to restore it manually using pwr button.

**Comment by syssi** [comment]
What do you mean by "discover don't find anything"? This custom component doesn't auto-discover the device. You have to use this configuration:

```
fan:
  - platform: xiaomi_miio_airpurifier
    host: 192.168.2.60
    token: f48b728634eedxxxxxxxxxx1a13ef8ebf646
    name: Purificatore Aria
```

**Comment by jokerigno** [comment]
Uhm ok changed to this:

```
fan:
  # Xiaomi Air Purifier 2S
  - platform: xiaomi_miio_airpurifier
    host: 192.168.2.60
    token: xxxxxxxxxx
    name: Purificatore Aria
```

I changed also token because usig get_token  I noticed it changed after repairing.

Host is correct (checked with unifi controller) and device is connected (checked with xiaomi app on ios).

I rebooted but no fan is added to my config (checked in dev tools).

**Comment by jokerigno** [comment]
Hi,

still no trace of the purifier. Logs does not report any error related to the custom component. Any hint or test that we can do?

**Comment by syssi** [comment]
Did you solve the issue?

**Comment by jokerigno** [comment]
Yes. I had  to reset purifier and change token. Now it works again as expected.
