### ISSUE TITLE
Updating xiaomi_miio_xxx took longer than the scheduled update interval 0:00:30

### ISSUE THREAD

**Issue by jpleite** [syssi/xiaomi_airpurifier#189]
I'm constantly getting this message along with "Got exception while fetching the state: No response from the device" for 2 devices (deerma.humidifier.jsq). Running latest HA

**Comment by syssi** [comment]
You could decrease the log level of the custom component.

**Comment by jpleite** [comment]
Thanks for your prompt response. I’ll do it.

**Comment by syssi** [comment]
This could be used as starting point: https://github.com/syssi/xiaomi_airpurifier#debugging

In this case you want t decrease the verbosity instead of increasing.
