### ISSUE TITLE
Xiaomi Humidifiert Device "unknown"

### ISSUE THREAD

**Issue by mlinko6** [syssi/xiaomi_airpurifier#193]
Hi,

I've tried to integrate my Humidifier with Xiaomi Miio:

Name: Humidifier
Model: deerma.humidifier.jsq
IP: 192.168.5.15
MAC: 64:90:C1:C8:AA:58
Token: da833d7ca2386e3466f455a928xxxxxx
Serial: ZNJSQ01DEM

I get the following Error:

The device model is not known, not able to setup the device using config flow.

I've also installed the custom component but I can't integrate it.

Thank you for your help!

KR
Rok

**Comment by syssi** [comment]
The device is supported if you use this custom component instead of the official integration.
