### ISSUE TITLE
 no custom component in the integration menu

### ISSUE THREAD

**Issue by mLihs** [syssi/xiaomi_airpurifier#194]
Hi,

will there be support for MISmartFan 3 (zhimi.fan.za5) soon?

**Comment by sasholinia** [comment]
Hi, 
i've added the custom component for the Pedestal Fan Fan 1C but I can't find the integration on the HA integration list. Am I doing something wrong?
thanks

**Comment by syssi** [comment]
You doing something wrong. ;-) This component is configured via `configuration.yaml` and has no integration record. As soon the custom component is loaded (via configuration.yaml) you should see a new `fan` entity with some attributes attached.

**Comment by mLihs** [comment]
Worked for me there was some Issue with my docker container setup
