### ISSUE TITLE
fan.set_speed doesn't work on Humidifier?

### ISSUE THREAD

**Issue by leotantantan** [syssi/xiaomi_airpurifier#195]
Hi, I'm new here, I'm trying to configure my Mijia Smart Sterilization Humidifier S(deerma.humidifier.mjjsq) with your integration. everything looks good so far, but it doesn't work when I use

input_select:
  airpurifier_mode:
    name: Operation mode
    options:
     - Low
     - Medium
     - High
     - Humidity

automation:
  - alias: Select operation mode by input select
    trigger:
      entity_id: input_select.airpurifier_mode
      platform: state
    action:
      service: fan.set_speed
      data_template:
        entity_id: fan.xiaomi_air_humidifier
        speed: '{{ states.input_select.airpurifier_mode.state }}'

  - alias: Monitor operation mode and update input select
    trigger:
      platform: state
      entity_id: fan.xiaomi_air_humidifier
    action:
      service: input_select.select_option
      entity_id: input_select.airpurifier_mode
      data_template:
        option: '{{ states.fan.xiaomi_air_purifier.attributes.speed }}'

I've replace entity_id: fan.xiaomi_air_purifier to fan.xiaomi_air_humidifier, is that right?

But it seems nothing happen when I change mode, and can't get the live mode data back. anyone can help?

**Comment by Guusda** [comment]
I am experiencing the same issue. My goal is to set the preset_mode of my `deerma.humidifier.jsq1`. 

input_select:
  airpurifier_mode:
    name: Operation mode
    options:
     - Low
     - Medium
     - High
     - Humidity

automation:
  - alias: Select operation mode by input select
    trigger:
      entity_id: input_select.airpurifier_mode
      platform: state
    action:
      service: fan.set_preset_mode
      data_template:
        entity_id: fan.mi_smart_antibacterial_humidifier
        preset_modes: '{{ states.input_select.airpurifier_mode.state }}'

  - alias: Monitor operation mode and update input select
    trigger:
      platform: state
      entity_id: fan.mi_smart_antibacterial_humidifier
    action:
      service: input_select.select_option
      entity_id: input_select.airpurifier_mode
      data_template:
        option: '{{ states.fan.mi_smart_antibacterial_humidifier.attributes.mode }}'

The logs show nothing of importance

**Comment by Guusda** [comment]
Hey @leotantantan I managed to figure out a solution for my HA instance. Take a look at the following piece of code, which helped me understand the interactions some attributes have with the purifier.

`airhumidifier_mode:
        friendly_name: "Mode"
        value_template: "{{ is_state_attr('fan.mi_smart_antibacterial_humidifier', 'preset_modes', 'Low') }}"
        turn_on:
          service: fan.set_preset_mode
          data:
            entity_id: fan.mi_smart_antibacterial_humidifier
            preset_mode: "low"
        turn_off:
          service: fan.set_preset_mode
          data:
            entity_id: fan.mi_smart_antibacterial_humidifier
            preset_mode: "medium"`

If you want to apply this to your own system, remember to change the `entity_id` to the id of your own device.

If you understand the piece of code, try to understand the following (which is actually how I managed to solve the solution, in my case).

`input_select:
  airhumidifier_mode:
    name: Mode
    options:
      - low
      - medium
      - high
      - humidity
    icon: "mdi:animation-outline"
    
automation input_mode:
  - alias: Air Humidifier Mode Change
    trigger: 
      entity_id: input_select.airhumidifier_mode
      platform: state
    action:
      service: fan.set_preset_mode
      data:
        entity_id: fan.mi_smart_antibacterial_humidifier
        preset_mode: '{{ states.input_select.airhumidifier_mode.state }}'
  - alias: Air Humidifier Mode Change
    trigger:
      platform: state
      entity_id: input_select.airhumidifier_mode
      data:
        option: '{{ states.fan.mi_smart_antibacterial_humidifier.attributes.mode }}'`

Hopefully it helps!

**Comment by va77** [comment]
Hi.
I faced with the same issue and I didn't find any solution like "copy-paste", so after some time I solved it:

  - alias: Select operation mode by input select
    trigger:
      entity_id: input_select.airpurifier_mode
      platform: state
    action:
      service: fan.set_preset_mode
      data_template:
        entity_id: fan.uvlazhnitel_vozdukha
        preset_mode: '{{ states.input_select.airpurifier_mode.state }}'

  - alias: Monitor operation mode and update input select
    trigger:
      platform: state
      entity_id: fan.uvlazhnitel_vozdukha
    action:
      service: input_select.select_option
      entity_id: input_select.airpurifier_mode
      data_template:
        option: '{{ states.fan.uvlazhnitel_vozdukha.attributes.preset_mode }}'

Don't forget to change entity_id

**Comment by syssi** [comment]
It looks like this is just a question and now issue + it's already solved.
