### ISSUE TITLE
HA 2021.9.2 (nwt.derh.wdh318efw1) - AttributeError: 'AirDehumidifier' object has no attribute 'device_info

### ISSUE THREAD

**Issue by peterhoe** [syssi/xiaomi_airpurifier#206]
Have tried with both V0.6.11 & V0.6.12

Was functioning fine with HaasV2021.8.8 using V0.6.11

On updating to HaasV2021.9.2 i started seeing this error

Error message as follows

Logger: homeassistant.components.climate
Source: custom_components/xiaomi_miio_airpurifier/climate.py:435
Integration: Climate (documentation, issues)
First occurred: 16:40:41 (2 occurrences)
Last logged: 16:40:41

xiaomi_miio_airpurifier: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
    await task
  File "/config/custom_components/xiaomi_miio_airpurifier/climate.py", line 435, in async_update
    state = await self.hass.async_add_executor_job(self._device.status)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/miio/airdehumidifier.py", line 201, in status
    if self.device_info is None:
AttributeError: 'AirDehumidifier' object has no attribute 'device_info'

**Comment by syssi** [comment]
`pythion-miio` has changed a bit. This custom component needs to be updated to be compatible again.

**Comment by tehnoinstyle** [comment]
Same problem on deerma.humidifier.mjjsq after update HA on V2021.9.2

Not work Xiaomi Air Humidifier and in log error:

`Logger: custom_components.xiaomi_miio_airpurifier.fan
Source: custom_components/xiaomi_miio_airpurifier/fan.py:1674
Integration: xiaomi_miio_airpurifier (documentation, issues)
First occurred: 12:59:30 (2 occurrences)
Last logged: 13:00:00

Got exception while fetching the state: {'code': -10000, 'message': 'Resp general error.'}`

with both V0.6.11 & V0.6.12

**Comment by peterhoe** [comment]
> `pythion-miio` has changed a bit. This custom component needs to be updated to be compatible again.

Anything I can do to help?

If you give me an example on one device what changes are required, perhaps I can go through and amend?

**Comment by syssi** [comment]
Go to the release page of the `python-miio` repository and take a look at the diff file of the last releases. `device_info` should be mentioned here. Was it removed or moved? Adapt the custom component to access `device_info` properly again.

**Comment by syssi** [comment]
@rytilahti Could you help me here? It looks like `device_info` isn't available anymore as property of the AirDehumidifier device class. Probably just a initialization is missing? I don't understand this line because of my limited python skills:

https://github.com/rytilahti/python-miio/blob/master/miio/airdehumidifier.py#L177

I would like to replace this line by

```
        self.device_info = None
```

to fix the issue.

**Comment by rytilahti** [comment]
@syssi oops, the initialization is indeed missing, that slipped somehow through the cracks when the variable got type hinted. It should look like this: https://github.com/rytilahti/python-miio/blob/master/miio/airhumidifier.py#L265

**Comment by nielsfaber** [comment]
Having the same problem here.
If I understand correctly, the problem is caused by the version of `python-miio` which is included with HA?
Is there any way to quick-fix this myself locally?

**Comment by syssi** [comment]
Fixed.

**Comment by peterhoe** [comment]
Confirmed functional with V0.6.16 & Haas V 2021.12.3
