### ISSUE TITLE
Add deerma.humidifier.jsq5 support

### ISSUE THREAD

**Issue by toyan** [syssi/xiaomi_airpurifier#207]
miiocli device info:
Model: deerma.humidifier.jsq5
Hardware version: esp8266
Firmware version: 2.0.7

**Comment by JuneManUA** [comment]
Hi there, I have faced the same issue.
Unsupported device found! 
```
deerma.humidifier.jsq5
Firmware version: 2.1.3
```

**Comment by re-id** [comment]
+

**Comment by dpozimski** [comment]
I have the same issue

**Comment by dpozimski** [comment]
I've created pull request for it:
https://github.com/syssi/xiaomi_airpurifier/pull/209
please review it

**Comment by syssi** [comment]
Device support added by #209. Kudos to @dpozimski 

Please give it a try!

**Comment by re-id** [comment]
HA accepts saving configuration with deerma.humidifier.jsq5
But there is still an error in integration
P.S. Sorry for my English

Logger: custom_components.xiaomi_miio_airpurifier.fan
Source: custom_components/xiaomi_miio_airpurifier/fan.py:1687
Integration: xiaomi_miio_airpurifier (documentation, issues)
First occurred: 11:12:06 (16 occurrences)
Last logged: 11:19:40
Got exception while fetching the state: {'code': -9999, 'message': 'user ack timeout'}

fan:

platform: xiaomi_miio_airpurifier
name: Xiaomi Air
host: 192.168.38.40
token: 879faba276a3f749630a8299a6ef5c48
model: deerma.humidifier.jsq5

**Comment by DmitryTankovich** [comment]
I have same error
2021-09-28 00:04:04 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

**Comment by JuneManUA** [comment]
I don't have any error in the log but unfortunately, the humidifier didn't appear  in entities


**fan.yaml**
```
- platform: xiaomi_miio_airpurifier
  name: doe_mi_humidifier
  model: deerma.humidifier.jsq5
  host: !secret xiaomi_humidifie_host
  token: !secret xiaomi_humidifie_token
```
