### ISSUE TITLE
Error 'mappingproxy object' has no attribute update Haas V 2021.9.2 - Air Purifier V3 (zhimi.airpurifier.v3)

### ISSUE THREAD

**Issue by peterhoe** [syssi/xiaomi_airpurifier#208]
Have tried with both V0.6.11 & V0.6.12

Was functioning fine with HaasV2021.8.8 using V0.6.11

On updating to HaasV2021.9.2 i started seeing this error

Error message as follows

Logger: homeassistant.helpers.template
Source: helpers/template.py:1485
First occurred: 06:41:09 (75 occurrences)
Last logged: 06:42:20

Template variable warning: 'mappingproxy object' has no attribute 'motor_speed' when rendering '{{ states.fan.airpurifier_lounge_2.attributes.motor_speed }}'
Template variable warning: 'mappingproxy object' has no attribute 'motor2_speed' when rendering '{{ states.fan.airpurifier_lounge_2.attributes.motor2_speed }}'
Template variable warning: 'mappingproxy object' has no attribute 'filter_type' when rendering '{{ states.fan.airpurifier_lounge_2.attributes.filter_type }}'
Template variable warning: 'mappingproxy object' has no attribute 'illuminance' when rendering '{{ states.fan.airpurifier_lounge_2.attributes.illuminance }}'
Template variable warning: 'mappingproxy object' has no attribute 'volume' when rendering '{{ states.fan.airpurifier_lounge_2.attributes.volume }}'

**Comment by syssi** [comment]
Could you provide a screenshot of your `fan.airpurifier_lounge_2` entity? I want to make sure you are using this custom component (and you are not using the official component).

**Comment by peterhoe** [comment]
> Could you provide a screenshot of your `fan.airpurifier_lounge_2` entity? I want to make sure you are using this custom component (and you are not using the official component).

Doh, My bad, very sorry for this.  I had commented out the custom component portion for the airpurifier Model zhimi.airpurifier.v7

Al functional for zhimi.airpurifier.v7 using V0.6.2
