### ISSUE TITLE
Add deerma.humidifier.jsq4 support

### ISSUE THREAD

**Issue by easuvorov** [syssi/xiaomi_airpurifier#217]
Hi,
is it possible to add support for Evaporative Humidifier deerma.humidifier.jsq4 (CJSJSQ01DY). This one seems similar to other **deerma** devices apart from that it doesn't report water level via Mi Home - only humidity is provided. Mi Home app allows to turn on / off, switch modes (1 - low, 2 - high, 3 - target humidity), setting target humidity level and configure led / buzzer.

I installed this repository via HACS, then configured device as following:
climate:
  - platform: xiaomi_miio_airpurifier
    name: Evaporative Humidifier
    host: xxx.xxx.xxx.xxx
    token: ...

Thanks in advance.

**Comment by drschmurge1** [comment]
Hi,
you may add it via homebridge and HA integration "Homekit Controller", i did it and it works. The plugin is called Homebridge Miot. My config in homebridge:
{
    "devices": [
        {
            "name": "Humidifier",
            "ip": "192.168.0.121",
            "token": "your_token",
            "deviceId": "14",
            "pollingInterval": 7,
            "deepDebugLog": false,
            "micloud": {
                "timeout": 5000
            },
            "buzzerControl": true,
            "ledControl": true,
            "swingControl": false,
            "fanLevelControl": true,
            "modeControl": true,
            "showTemperature": false
        }
    ],
    "platform": "miot"
}

**Comment by ertoron** [comment]
any updates?

**Comment by SandDeath** [comment]
Are there any updates?  can i help you with something?

**Comment by Grawl** [comment]
https://github.com/syssi/xiaomi_airpurifier/issues/109

**Comment by syssi** [comment]
This is a duplicate of #109.
