### ISSUE TITLE
Add support for data: roborock.vacuum.s4

### ISSUE THREAD

**Issue by theglus** [syssi/xiaomi_airpurifier#219]
I'm currently receiving the following error for my [Xiaomi Miio vacuum integration](https://www.home-assistant.io/integrations/xiaomi_miio#xiaomi-mi-robot-vacuum). 

```
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:142
Integration: Xiaomi Miio (documentation, issues)
First occurred: 3:38:14 PM (1 occurrences)
Last logged: 3:38:14 PM

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: roborock.vacuum.s4
```

**Comment by syssi** [comment]
This custom component is about different Airpurifier models. This is not the right place to add vacuum support.

**Comment by theglus** [comment]
> This custom component is about different Airpurifier models. This is not the right place to add vacuum support.

@syssi would you mind pointing me in the right direction. There error in Home Assistant pointed my to this repository. 

![Screenshot_20211030-154022.png](https://user-images.githubusercontent.com/2943783/139572554-2a69acd1-4130-494b-80be-1b023f2c76bf.png)

**Comment by syssi** [comment]
Ups! I didn't know this repository is mentioned at the official component. At first your device must be implemented in / support d of the underlying library (https://github.com/rytilahti/python-miio). The second step is to add the new device to the official HA component. Feature requests shouldn't filed as `issue` here. Please use the "feature request" section of the HA community.

**Comment by syssi** [comment]
You are a lucky guy: https://github.com/home-assistant/core/pull/58682

Your device is officially supported soon!
