### ISSUE TITLE
Roborock vacuum was working, now "isn't supported"?

### ISSUE THREAD

**Issue by dzazzo** [syssi/xiaomi_airpurifier#220]
I don't really understand - this was working just fine, and now isn't.  Please add support for roborock.vacuum.a08.  Thanks.

**Comment by matata86** [comment]
same problem after update to 2021.11

**Comment by xuefer** [comment]
same goes with roborock.vacuum.t6

#222 is duplicate of this issue

**Comment by syssi** [comment]
Please update to 2021.11.1. This should fix the issue.
