### ISSUE TITLE
deerma.humidifier.jsq state is unavailable

### ISSUE THREAD

**Issue by ZuyRzuuf** [syssi/xiaomi_airpurifier#221]
Mi Smart Antibacterial Humidifier state configured as deerma.humidifier.jsq is unavailable.
![humidifier_issue](https://user-images.githubusercontent.com/4593555/140032209-b1e99f1f-80df-4eea-980a-2309868be45e.png)

**Comment by ZuyRzuuf** [comment]
It was an issue with token, not a package

**Comment by chrisrosenkreuz23** [comment]
I have the same model and it still frequently becoming unavailable like every 15 minutes or so (even the local integration).  Can you please provide details as to what you did to resolve?
