### ISSUE TITLE
HA 2021.11 unsupported roborock.vacuum.c1

### ISSUE THREAD

**Issue by rotem925** [syssi/xiaomi_airpurifier#222]
As in the subject,
With the latest version roborock.vacuum.c1 is not supported.

**Comment by jeanofthedead** [comment]
I'm getting the same error for roborock.vacuum.a01 (RoboRock E4) after updating HomeAssistant to 2021.11.0 today.

**Comment by DrKatozzo** [comment]
Same problem with
roborock.vacuum

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: roborock.vacuum

**Comment by tsebukas** [comment]
Same with roborock.vacuum.m1s

**Comment by kwatkins** [comment]
+1

**Comment by rytilahti** [comment]
https://github.com/home-assistant/core/pull/59018 which will be in the .1 release fixes this issue.

**Comment by syssi** [comment]
Please update to 2021.11.1. This should fix the issue.

**Comment by rotem925** [comment]
Still issues there.
I can see this in the log, even after reinstalling the integration:

Logger: homeassistant.config_entries
Source: components/xiaomi_miio/__init__.py:457
First occurred: 8:40:08 AM (4 occurrences)
Last logged: 8:49:35 AM

Error unloading entry Basement Robot vacuum for xiaomi_miio
Error unloading entry roborock.vacuum.c1 for xiaomi_miio
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/__init__.py", line 457, in async_unload_entry
    hass.data[DOMAIN].pop(config_entry.entry_id)
KeyError: 'XXXXXXXXXXXXXXXXXXX'

Replaced the key error...

**Comment by syssi** [comment]
Could you create an issue at the HA core repository? Sorry for the trouble.

**Comment by rotem925** [comment]
Ok, just did. https://github.com/home-assistant/core/issues/59136
