### ISSUE TITLE
HA 2021.11 - Unsupported device found: roborock.vacuum

### ISSUE THREAD

**Issue by bjohnson8949** [syssi/xiaomi_airpurifier#224]
Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: roborock.vacuum

**Comment by nicespoon** [comment]
Same message here. I have a Xiaomi Mi Robot Vacuum (1st gen).

**Comment by syssi** [comment]
Please update to 2021.11.1. This should fix the issue.
