### ISSUE TITLE
roborock.vacuum.m1s unsupported

### ISSUE THREAD

**Issue by basdejong95** [syssi/xiaomi_airpurifier#225]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:142
Integration: Xiaomi Miio (documentation, issues)
First occurred: 10:01:17 PM (2 occurrences)
Last logged: 10:08:28 PM

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: roborock.vacuum.m1s

**Comment by syssi** [comment]
Please update to 2021.11.1. This should fix the issue.
