### ISSUE TITLE
Please add support for a device 'deerma.humidifier.jsq5'

### ISSUE THREAD

**Issue by kvladimirovich10** [syssi/xiaomi_airpurifier#229]

**Comment by aerosh** [comment]
The humidifier is supported but does not work.
https://github.com/syssi/xiaomi_airpurifier/issues/213
I also ran into this problem :(
The proposed integration is not very convenient.

**Comment by pavelslunin** [comment]
I have the same issue with deerma.humidifier.jsq5 in Xiaomi Miio integration.

**Comment by alexhyriavets** [comment]
+
have the same problem.

**Comment by cosmaz** [comment]
same problem

2021-11-20 09:28:12 DEBUG (SyncWorker_2) [miio.miioprotocol] Discovered 18977620 with ts: 1970-01-01 08:42:34, token: b'ffffffffffffffffffffffffffffffff'
2021-11-20 09:28:12 DEBUG (SyncWorker_2) [miio.miioprotocol] 192.168.1.134:54321 >>: {'id': 1, 'method': 'get_prop', 'params': ['OnOff_State']}
2021-11-20 09:28:16 DEBUG (SyncWorker_2) [miio.miioprotocol] 192.168.1.134:54321 (ts: 1970-01-01 08:42:39, id: 1) << {'id': 1, 'error': {'code': -9999, 'message': 'user ack timeout'}, 'exe_time': 4020}
2021-11-20 09:28:16 ERROR (MainThread) [custom_components.xiaomi_miio_airpurifier.fan] Got exception while fetching the state: {'code': -9999, 'message': 'user ack timeout'}


INFO:miio.cli:Debug mode active
DEBUG:miio.miioprotocol:Got a response: Container: 
    data = Container: 
        data = b'' (total 0)
        value = b'' (total 0)
        offset1 = 32
        offset2 = 32
        length = 0
    header = Container: 
        data = b'!1\x00 \x00\x00\x00\x00\x18\x97v \x00\x00u\x88' (total 16)
        value = Container: 
            length = 32
            unknown = 0
            device_id = unhexlify('18977620')
            ts = 1970-01-01 08:21:28
        offset1 = 0
        offset2 = 16
        length = 16
    checksum = b'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff' (total 16)
DEBUG:miio.miioprotocol:Discovered 18977620 with ts: 1970-01-01 08:21:28, token: b'ffffffffffffffffffffffffffffffff'
DEBUG:miio.miioprotocol:192.168.1.134:54321 >>: {'id': 1, 'method': 'get_properties', 'params': [{'did': 'power', 'siid': 2, 'piid': 2}, {'did': 'fan_level', 'siid': 2, 'piid': 4}, {'did': 'mode', 'siid': 2, 'piid': 5}, {'did': 'humidity', 'siid': 3, 'piid': 7}, {'did': 'temperature', 'siid': 3, 'piid': 8}, {'did': 'aqi', 'siid': 3, 'piid': 6}, {'did': 'filter_life_remaining', 'siid': 4, 'piid': 3}, {'did': 'filter_hours_used', 'siid': 4, 'piid': 5}, {'did': 'buzzer', 'siid': 5, 'piid': 1}, {'did': 'buzzer_volume', 'siid': 5, 'piid': 2}, {'did': 'led_brightness', 'siid': 6, 'piid': 1}, {'did': 'led', 'siid': 6, 'piid': 6}, {'did': 'child_lock', 'siid': 7, 'piid': 1}, {'did': 'favorite_level', 'siid': 10, 'piid': 10}, {'did': 'favorite_rpm', 'siid': 10, 'piid': 7}]}
DEBUG:miio.miioprotocol:192.168.1.134:54321 (ts: 1970-01-01 08:21:32, id: 1) << {'id': 1, 'result': [{'did': 'power', 'siid': 2, 'piid': 2, 'code': 0, 'value': 0}, {'did': 'fan_level', 'siid': 2, 'piid': 4, 'code': 2}, {'did': 'mode', 'siid': 2, 'piid': 5, 'code': -4004}, {'did': 'humidity', 'siid': 3, 'piid': 7, 'code': 0, 'value': 26}, {'did': 'temperature', 'siid': 3, 'piid': 8, 'code': 3}, {'did': 'aqi', 'siid': 3, 'piid': 6, 'code': -4004}, {'did': 'filter_life_remaining', 'siid': 4, 'piid': 3, 'code': -4004}, {'did': 'filter_hours_used', 'siid': 4, 'piid': 5, 'code': 5}, {'did': 'buzzer', 'siid': 5, 'piid': 1, 'code': -4004}, {'did': 'buzzer_volume', 'siid': 5, 'piid': 2, 'code': -4004}, {'did': 'led_brightness', 'siid': 6, 'piid': 1, 'code': -4004}, {'did': 'led', 'siid': 6, 'piid': 6, 'code': -4004}, {'did': 'child_lock', 'siid': 7, 'piid': 1, 'code': -4004}, {'did': 'favorite_level', 'siid': 10, 'piid': 10, 'code': -4004}, {'did': 'favorite_rpm', 'siid': 10, 'piid': 7, 'code': -4004}], 'exe_time': 3080}
DEBUG:miio.miioprotocol:192.168.1.134:54321 >>: {'id': 2, 'method': 'get_properties', 'params': [{'did': 'motor_speed', 'siid': 10, 'piid': 8}, {'did': 'use_time', 'siid': 12, 'piid': 1}, {'did': 'purify_volume', 'siid': 13, 'piid': 1}, {'did': 'average_aqi', 'siid': 13, 'piid': 2}, {'did': 'filter_rfid_tag', 'siid': 14, 'piid': 1}, {'did': 'filter_rfid_product_id', 'siid': 14, 'piid': 3}, {'did': 'app_extra', 'siid': 15, 'piid': 1}]}
DEBUG:miio.miioprotocol:192.168.1.134:54321 (ts: 1970-01-01 08:21:32, id: 2) << {'id': 2, 'result': [{'did': 'motor_speed', 'siid': 10, 'piid': 8, 'code': -4004}, {'did': 'use_time', 'siid': 12, 'piid': 1, 'code': -4004}, {'did': 'purify_volume', 'siid': 13, 'piid': 1, 'code': -4004}, {'did': 'average_aqi', 'siid': 13, 'piid': 2, 'code': -4004}, {'did': 'filter_rfid_tag', 'siid': 14, 'piid': 1, 'code': -4004}, {'did': 'filter_rfid_product_id', 'siid': 14, 'piid': 3, 'code': 1}, {'did': 'app_extra', 'siid': 15, 'piid': 1, 'code': -4004}], 'exe_time': 240}
DEBUG:miio.airpurifier_miot:Unknown mode: None
Power: off
AQI: None μg/m³
Average AQI: None μg/m³
Humidity: 26 %
Temperature: None °C
Fan Level: None
Mode: OperationMode.Unknown
LED: None
LED brightness: None
Buzzer: None
Buzzer vol.: None
Child lock: None
Favorite level: None
Filter life remaining: None %
Filter hours used: None
Use time: None s
Purify volume: None m³
Motor speed: None rpm
Filter RFID product id: None
Filter RFID tag: None
Filter type: None

**Comment by grucha532** [comment]
Same here:

Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:106
Integration: Xiaomi Miio (documentation, issues)
First occurred: 6:41:27 PM (2 occurrences)
Last logged: 9:03:55 PM

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

**Comment by accu0** [comment]
Same here:

Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:144
Integration: Xiaomi Miio (documentation, issues)
First occurred: 23:16:13 (1 occurrences)
Last logged: 23:16:13

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

**Comment by kvladimirovich10** [comment]
Well, as it was mentioned in https://github.com/syssi/xiaomi_airpurifier/issues/213

This: https://github.com/al-one/hass-xiaomi-miot 
works just fine ✅

**Comment by mrkesu** [comment]
Same here :)

**Comment by joaoasrosa** [comment]
I'm another  user with the same issue. 

```
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:144
Integration: Xiaomi Miio (documentation, issues)
First occurred: 15:28:25 (1 occurrences)
Last logged: 15:28:25

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5
```

In the meantime will use the alternative installation

**Comment by Krzysztonek** [comment]
Here is the same issue:

![image](https://user-images.githubusercontent.com/87784133/145466939-93c68b71-262c-4352-a522-ae2c6fcd74f2.png)

**Comment by Krzysztonek** [comment]
Here is the same issue:

![image](https://user-images.githubusercontent.com/87784133/145466939-93c68b71-262c-4352-a522-ae2c6fcd74f2.png)

**Comment by syssi** [comment]
Let's discuss all details here #213.
