### ISSUE TITLE
Add deerma.humidifier.jsq3 support

### ISSUE THREAD

**Issue by Nik-Targon** [syssi/xiaomi_airpurifier#233]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:144
Integration: Xiaomi Miio (documentation, issues)

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq3

**Comment by Delliaf** [comment]
Same thing

**Comment by syssi** [comment]
Dupllicate #123 and will be fixed by #266.
