### ISSUE TITLE
Implements device_state_attributes

### ISSUE THREAD

**Issue by RaulVKoNe** [syssi/xiaomi_airpurifier#238]
After upgrading to Home Assistant 2021.12.0:

Entity fan.xiaomi_air_humidifier (<class 'custom_components.xiaomi_miio_airpurifier.fan.XiaomiAirHumidifierMjjsq'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by syssi** [comment]
Fixed in `0.6.15`.
