### ISSUE TITLE
zhimi.humidifier.cb1: Fix water_level attribute and check temperature

### ISSUE THREAD

**Issue by megachammer** [syssi/xiaomi_airpurifier#239]
I have noticed that temperature attribute is broken. Also, add please "water_level" for zhimi.humidifier.cb1. I have made it by myself in fan.py and it is working correctly.
By the way, sometimes after HA reboot humidifier become unavalible and I really don't know what happens. 
<img width="298" alt="image" src="https://user-images.githubusercontent.com/19786428/146527100-6f3e97b5-9d16-46d7-9072-1ff4bad61f6f.png">

**Comment by syssi** [comment]
Could you provide some details about your fix?

**Comment by megachammer** [comment]
![Screenshot_20211218-204020](https://user-images.githubusercontent.com/19786428/146650646-20e3c9f8-52ff-4523-a713-d24a167bb759.jpg)
My fix is very simple and it is about water_level but not about temperature.

**Comment by syssi** [comment]
Are you sure you are using the most recent version of this component? Please check this line of code:

https://github.com/syssi/xiaomi_airpurifier/blob/develop/custom_components/xiaomi_miio_airpurifier/fan.py#L501

Do you think there should be changed something? May be I missed your point.

**Comment by megachammer** [comment]
Yes, I am sure :) I guess I have made a mistake at previous picture marking the wrong part of code. Look at the new one, I am telling you about cb1 model
![Screenshot_20211218-224448](https://user-images.githubusercontent.com/19786428/146653972-f95a15be-a992-460c-b7bb-dc1c3eee5212.jpg)

**Comment by syssi** [comment]
I've added two new attributes: `water_level ` and `water_tank_detached`. Please give it a try!

**Comment by syssi** [comment]
Could you try to retrieve the temperature property directly by `miiocli` (it's provied by `pip3 install python-miio`): 

```
miiocli device --ip <IP> --token <TOKEN> raw_command get_prop '["temperature"]'
miiocli device --ip <IP> --token <TOKEN> raw_command get_prop '["temp_dec"]'
```

I want to make sure your device is able to provide some temperature values.

**Comment by megachammer** [comment]
> I've added two new attributes: `water_level ` and `water_tank_detached`. Please give it a try!
![image](https://user-images.githubusercontent.com/19786428/146655628-bc1e495d-a311-4fcc-a362-5a3cb2c8fc6d.png)
Unfortunatly no water_level after HACS update

**Comment by syssi** [comment]
I didn't prepare a release yet. So HACS isn't aware of the recent change. I will prepare a release later the day and ping you.

**Comment by syssi** [comment]
Done. Please give it another try using version 0.6.17.

**Comment by megachammer** [comment]
Something strange happened. After updating to version 0.6.17 and restarting HA zhimi.humidifier.cb1 became unavailable. I've tried to reboot server several times with no luck :(

**Comment by syssi** [comment]
This is strange. Could you check the log? Do you see any errors here?

**Comment by megachammer** [comment]
I think this is the [solution](https://community.home-assistant.io/t/xiaomi-miio-not-working-since-release-2021-10-x/346401) for my problem. One custom integration had a wrong manifest.json. Now everythink work fine (including two new attributes) exept temperarure. Thenx!
If you could give me more detailed instruction how to check raw_command I will check it.
<img width="278" alt="image" src="https://user-images.githubusercontent.com/19786428/146677324-ff142b36-b3bf-4ae7-8584-02c731125e35.png">

**Comment by syssi** [comment]
Good job! Could you detach the water tank once to make sure the "water tank detached" attribute works as expected?

Next step: Do you have access to an linux host or SSH access to a rasperry pi running linux? Please install python-miio by:

```
$ sudo apt-get install python3-pip
$ pip3 install python-miio
Collecting python-miio
  Using cached python_miio-0.5.9.2-py3-none-any.whl (304 kB)
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from python-miio) (2021.1)
Collecting construct<3.0.0,>=2.10.56
  Using cached construct-2.10.67-py3-none-any.whl
Collecting defusedxml<1,>=0
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting tqdm<5,>=4
  Using cached tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Requirement already satisfied: click>=7 in ./.local/lib/python3.9/site-packages (from python-miio) (8.0.3)
Collecting android_backup<1,>=0
  Using cached android_backup-0.2.0-py3-none-any.whl
Requirement already satisfied: PyYAML<7,>=5 in ./.local/lib/python3.9/site-packages (from python-miio) (6.0)
Collecting cryptography>=35
  Downloading cryptography-36.0.1-cp36-abi3-manylinux_2_24_x86_64.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 5.0 MB/s 
Requirement already satisfied: attrs in /usr/lib/python3/dist-packages (from python-miio) (20.3.0)
Requirement already satisfied: appdirs<2,>=1 in /usr/lib/python3/dist-packages (from python-miio) (1.4.4)
Requirement already satisfied: zeroconf<1,>=0 in ./.local/lib/python3.9/site-packages (from python-miio) (0.36.13)
Collecting croniter>=1
  Using cached croniter-1.1.0-py2.py3-none-any.whl (17 kB)
Requirement already satisfied: netifaces<1,>=0 in /usr/lib/python3/dist-packages (from python-miio) (0.10.9)
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (from croniter>=1->python-miio) (2.8.1)
Collecting cffi>=1.12
  Using cached cffi-1.15.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (444 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Requirement already satisfied: ifaddr>=0.1.7 in /usr/lib/python3/dist-packages (from zeroconf<1,>=0->python-miio) (0.1.7)
Installing collected packages: pycparser, cffi, tqdm, defusedxml, cryptography, croniter, construct, android-backup, python-miio
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
esphome 2021.11.4 requires platformio==5.2.2, but you have platformio 5.2.3 which is incompatible.
Successfully installed android-backup-0.2.0 cffi-1.15.0 construct-2.10.67 croniter-1.1.0 cryptography-36.0.1 defusedxml-0.7.1 pycparser-2.21 python-miio-0.5.9.2 tqdm-4.62.3
sebastian@wolowitz:~$ .local/bin/miiocli      
Usage: miiocli [OPTIONS] COMMAND [ARGS]...

Options:
  -d, --debug
  -o, --output [default|json|json_pretty]
  --version                       Show the version and exit.
  --help                          Show this message and exit.

Commands:
  airconditionermiot
  airconditioningcompanion
  airconditioningcompanionmcn02
  airconditioningcompanionv3
[...]
```

Now you've access to the command line tool called `miiocli`. Please execute the command two times to retrieve two different properties via the `raw_command`:

```
miiocli device --ip <IP> --token <TOKEN> raw_command get_prop '["temperature"]'
miiocli device --ip <IP> --token <TOKEN> raw_command get_prop '["temp_dec"]'
```

**Comment by megachammer** [comment]
"water tank detached" works fine, thanx!
<img width="634" alt="image" src="https://user-images.githubusercontent.com/19786428/146679105-ea98d22a-f9d4-469a-a28e-b232cbd27ad8.png">

Is that you asking for?

**Comment by megachammer** [comment]
I think I know what the problem is.
I've got CJXJSQ02ZM and acording to your manual it should be zhimi.humidifier.cb1 but it is not.
<img width="116" alt="image" src="https://user-images.githubusercontent.com/19786428/146680220-1c4f870d-90ce-4ad8-9367-554adec4d702.png">
<img width="895" alt="image" src="https://user-images.githubusercontent.com/19786428/146680126-ae64b5ff-0497-468d-a2c0-a91d60f66e49.png">

When I change the model to zhimi.humidifier.ca1 in configuration.yaml the temperatute started to work.

**Comment by syssi** [comment]
```
miiocli device --ip <IP> --token <TOKEN> info
```

will return the model name of your device.

**Comment by syssi** [comment]
Ah! You've used the command alright. In this case there is no further fix needed here.

**Comment by syssi** [comment]
Could you provide a photo of your device type label? I would like to improve the README.

**Comment by megachammer** [comment]
![IMG_20211219_192427](https://user-images.githubusercontent.com/19786428/146682615-c938825e-cc13-4f84-b83f-c3860d99def5.jpg)
![IMG_20211219_192610](https://user-images.githubusercontent.com/19786428/146682617-5611678a-3197-4c06-a809-9fa23f1c7aed.jpg)

**Comment by syssi** [comment]
Thanks a lot!
