### ISSUE TITLE
average_aqi detail ?

### ISSUE THREAD

**Issue by tyjtyj** [syssi/xiaomi_airpurifier#24]
Hi,

Not really issue but information

Would you mind share how to does the average_aqi calculated ? 

Thanks you in advance for the great work

**Comment by syssi** [comment]
This is a property calculated by the device firmware. I cannot provide further details. The device just provides two properties (aqi & average_aqi).

**Comment by tyjtyj** [comment]
Thanks... I will calculate my own number then
..
