### ISSUE TITLE
Add support for zhimi.airpurifier.mb4

### ISSUE THREAD

**Issue by dlsnet** [syssi/xiaomi_airpurifier#244]
Hi. Would it be possible to add support for zhimi.airpurifier.mb4 (Mi Air Purifier 3C)?

It seems zhimi.airpurifier.ma4 / zhimi.airpurifier.mb3 don't exactly work for this model:

![image](https://user-images.githubusercontent.com/3121405/147691232-ad07bf83-9a33-4d14-a8ae-2191eed4c505.png)

**Comment by syssi** [comment]
Duplicate of #117.
