### ISSUE TITLE
Xiaomi Miio - zhimi.airpurifier.mb3 - unavailabel entities

### ISSUE THREAD

**Issue by matata86** [syssi/xiaomi_airpurifier#247]
Hi, i have unavaltable enetites few days...
![miiio](https://user-images.githubusercontent.com/28623294/148677718-e8baca1f-6ad9-43d4-ab7b-cb1940a73c3f.png)

**Comment by chimcanhcut1112** [comment]
same problem :(

**Comment by syssi** [comment]
Could you create an issue at the HA core repository? This lovelace cards doesn't belong to this custom component.
