### ISSUE TITLE
Unsupported device found! : deerma.humidifier.jsq5

### ISSUE THREAD

**Issue by RafZie** [syssi/xiaomi_airpurifier#248]
Hi
I got message like below i my logs 

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

is it possible to add this device?
thanks in advance 
rz

**Comment by thesorin** [comment]
+1

**Comment by sv-kov** [comment]
+1

**Comment by neocaine** [comment]
+1

**Comment by AndreOrth** [comment]
+1

**Comment by egor-spk** [comment]
+1

**Comment by Ghimpe-ro** [comment]
+1
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:154
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 8:56:50 PM (1 occurrences)
Last logged: 8:56:50 PM

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

**Comment by sv-kov** [comment]
I'm also following the decision. Here I added a temporary solution option.
https://github.com/syssi/xiaomi_airpurifier/issues/213

**Comment by michaelbing** [comment]
+1

**Comment by klimenko4** [comment]
+1

**Comment by dculprit** [comment]
+1

**Comment by Mothamoz** [comment]
Please add this device!
