### ISSUE TITLE
Add deerma.humidifier.jsq3 (MJJSQ04DY) support

### ISSUE THREAD

**Issue by Elektronik777** [syssi/xiaomi_airpurifier#249]
Hello. Please add support for the humidifier Mijia Humidifier 4L (MJJSQ04DY)

Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:154
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 14:34:12 (3 occurrences)
Last logged: 14:46:58

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq3

**Comment by Anonym-tsk** [comment]
Duplicate #233
