### ISSUE TITLE
Error after HA upgraded to Home Assistant 2022.3.0

### ISSUE THREAD

**Issue by keshabit** [syssi/xiaomi_airpurifier#254]
Configuration validation
Validate your configuration if you recently made some changes to your configuration and want to make sure that it is all valid.
Configuration invalid

Platform error fan.xiaomi_miio_airpurifier - No module named 'miio.fan'

PLS FIX THIS IMMEDIATELY!!

**Comment by syssi** [comment]
Please avoid to use caps lock at free software repositories / yelling at people. :-P

**Comment by syssi** [comment]
Duplicate of #253.

**Comment by keshabit** [comment]
> Please avoid to use caps lock at free software repositories / yelling at people. :-P 

It wasn't yelling rather communicating sense of urgency!! Upper case also signifies importance haha I write my surname in upper followed by name thus it's not yelling my friend!! Pls just resolve it, thanks.
