### ISSUE TITLE
How Can I add Button to Add control/Switch Operation modes (auto, silent, favorite, idle)

### ISSUE THREAD

**Issue by ceaswaran** [syssi/xiaomi_airpurifier#26]
Hi,
I am new to Home assistant
I managed to add Xiaomi Air purifier 2 to HA & successfully!!
 I am able to ON & OFF the device using Home Assitant UI

I want to add a button(s) to change the Operation Mode of the Xiaomi Air purifier 2 in Home assitant
Also, want to Display the following data in my Home assistant front page

1. temperature
2. humidity
3. aqi
4. mode
5. filter_hours_used
6. filter_life_remaining

Please help me with an example so that I can get the same

Thanks in advance.

**Comment by syssi** [comment]
This is the way to go: 

https://www.home-assistant.io/components/input_select/
https://www.home-assistant.io/components/sensor.template/

**Comment by syssi** [comment]
And take a look at this issue: https://github.com/syssi/xiaomi_airpurifier/issues/21

**Comment by ceaswaran** [comment]
Thanks a lot
I will take & look & implement if I have any issues ill post back

Thanks again

**Comment by syssi** [comment]
Please post you configuration (yaml).
