### ISSUE TITLE
Add support for deerma.humidifier.jsq5

### ISSUE THREAD

**Issue by t68ovidiu** [syssi/xiaomi_airpurifier#261]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:158
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: March 4, 2022, 10:54:54 PM (1 occurrences)
Last logged: March 4, 2022, 10:54:54 PM

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

**Comment by caro7372** [comment]
Same here: deerma.humidifier.jsq5 not supported

**Comment by tompostma** [comment]
Same issue here with the "Mi Slimme antibacterial Humidifier (model: ZNJSQ01DEM)":

Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:154
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 20:54:09 (1 occurrences)
Last logged: 20:54:09

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

**Comment by syssi** [comment]
If you use this custom component `xiaomi_miio_airpurifier` the device is already supported. It's not supported by the official HA core component `xiaomi_miio` right now.
