### ISSUE TITLE
I got Platform error

### ISSUE THREAD

**Issue by heejoochae** [syssi/xiaomi_airpurifier#267]
Platform error fan.xiaomi_miio_airpurifier - cannot import name 'AirDogX5' from 'miio' (/usr/local/lib/python3.9/site-packages/miio/__init__.py)

my config:

fan:
    - platform: xiaomi_miio_airpurifier
      host: 192.168.0.169
      token: !secret xiaomi_token
      name : Xiaomi Air Purifier
      model: zhimi.airpurifier.ma2

HA Version core-2022.3.3

**Comment by syssi** [comment]
Do you use the most recent version/release of this custom component?

**Comment by syssi** [comment]
Please update the custom component. The most recent version doesn't import/use the `AirDogX5` class anymore.

**Comment by heejoochae** [comment]
I redownload the component but didn't work
I removed the component and installed again. It's working.
Thank you.
