### ISSUE TITLE
Add deerma.humidifier.jsq5 support

### ISSUE THREAD

**Issue by no-compromise** [syssi/xiaomi_airpurifier#269]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:144
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 16:17:13 (1 occurrences)
Last logged: 16:17:13

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

Thank you

**Comment by Anonym-tsk** [comment]
Already added #257
Please update component

**Comment by syssi** [comment]
> Source: components/xiaomi_miio/init.py:144

You are using the official component. This custom component supports the `jsq5` already.
