### ISSUE TITLE
Unsupported device found! nwt.derh.wdh318efw1

### ISSUE THREAD

**Issue by sasukebinbin** [syssi/xiaomi_airpurifier#272]
Log shows
Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: nwt.derh.wdh318efw1

It should be support. And I forgot which version I used before it is supported.

**Comment by syssi** [comment]
You could use this custom component instead of the official integration. The device is supported here.
