### ISSUE TITLE
Issue to integrate Mi Smart Humidifier S

### ISSUE THREAD

**Issue by yapchoonkiat** [syssi/xiaomi_airpurifier#278]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:154
Integration: Xiaomi Miio (documentation, issues)
First occurred: 10:26:50 AM (3 occurrences)
Last logged: 11:30:07 AM

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsqs

**Comment by syssi** [comment]
The device is supported by this custom component. Please give it a try!
