### ISSUE TITLE
Add deerma.humidifier.jsqs support (Xiaomi Smart Sterilization Humidifier S (MJJSQ03DY))

### ISSUE THREAD

**Issue by DiamondLight0** [syssi/xiaomi_airpurifier#283]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:154
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 22:50:07 (1 occurrences)
Last logged: 22:50:07

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsqs

Model: Xiaomi Smart Sterilization Humidifier S (MJJSQ03DY)

**Comment by syssi** [comment]
You could use this custom component. The model is supported.
