### ISSUE TITLE
Platform error fan.xiaomi_miio_airpurifier - cannot import name 'AirHumidifierJsqs' from 'miio'

### ISSUE THREAD

**Issue by bimodinochka** [syssi/xiaomi_airpurifier#285]
The integration has been working stably for a while, but after several server reboots, the devices are no longer available and when I reboot, I get an error:

Platform error fan.xiaomi_miio_airpurifier - cannot import name 'AirHumidifierJsqs' from 'miio' (/usr/local/lib/python3.9/site-packages/miio/__init__.py)

We have to comment out the lines with the devices so that we can do a reboot.

But after this reconnection I get this error again.

If you do not use integration for a week or more (perhaps after HA updates) and then reconnect the devices, they will work again, but after a couple of server reboots everything starts over.

How can I fix this, I often work with HA and reboot it often and this becomes a problem for me.

But this is the best integration for my devices.

**Comment by krakowski** [comment]
I got the same error today after restarting. After some investigation I found out that the [homeassistant-vacuum-viomi](https://github.com/nergal/homeassistant-vacuum-viomi) depends on a older version of `python-miio` ([manifest.json](https://github.com/nergal/homeassistant-vacuum-viomi/blob/master/custom_components/xiaomi_viomi/manifest.json) contains `python-miio==0.5.9`) while this project uses `python-miio>=0.5.11` inside its [manifest.json](https://github.com/syssi/xiaomi_airpurifier/blob/develop/custom_components/xiaomi_miio_airpurifier/manifest.json). Version `0.5.9` does not contain `AirHumidifierJsqs` (see [\_\_init\_\_.py](https://github.com/rytilahti/python-miio/blob/0.5.9/miio/__init__.py)).

Changing the dependency inside `custom_components/xiaomi_miio_airpurifier/manifest.json` from `python-miio==0.5.9` to `python-miio>=0.5.11` and rebooting Home Assistant fixed the problem for me.

**Comment by bimodinochka** [comment]
> I got the same error today after restarting. After some investigation I found out that [homeassistant-vacuum-viomi](https://github.gitop.top/nergal/homeassistant-vacuum-viomi) depends on a older version of `python-miio` ([manifest.json](https://github.gitop.top/nergal/homeassistant-vacuum-viomi/blob/master/custom_components/xiaomi_viomi/manifest.json) contains `python-miio==0.5.9`) while this project uses `python-miio>=0.5.11` inside its [manifest.json](https://github.gitop.top/syssi/xiaomi_airpurifier/blob/develop/custom_components/xiaomi_miio_airpurifier/manifest.json). Version `0.5.9` does not contain `AirHumidifierJsqs` (see [__init__.py](https://github.gitop.top/rytilahti/python-miio/blob/0.5.9/miio/__init__.py)).
> 
> Changing the dependency inside `custom_components/xiaomi_miio_airpurifier/manifest.json` from `python-miio==0.5.9` to `python-miio>=0.5.11` and rebooting Home Assistant fixed the problem for me.


Thank you for your answer but unfortunately it doesn't work for me.
Besides, I don't use (homeassistant-vacuum-viomi) and mine (python-miio>=0.5.11) was originally version 0.5.11.

**Comment by re3lex** [comment]
I just got same issue after updating this component to the latest.
Using the info from this thread (thanks @krakowski !) I run search inside hass folder and found that `Xiaomi Cloud Map Extractor` component has `python-miio` in requirements though without exact version. 
So just replaced it with `python-miio>=0.5.11`, restarted HASS and the issue is gone.
