### ISSUE TITLE
The device with sid 158d00044b1b9d isn't supported of the used gateway firmware. Please update the gateway firmware if possible! This is the only way the issue can be solved.

### ISSUE THREAD

**Issue by 9pr** [syssi/xiaomi_airpurifier#287]
This is deerma.humidifier.jsq | ZNJSQ01DEM

Could you tell me please why don't work?

**Comment by syssi** [comment]
The error message (about a sub-device of a Xiaomi Gateway) is unrelated to your Air Humidifier.
