### ISSUE TITLE
deerma.humidifier.jsqs

### ISSUE THREAD

**Issue by pilotwarezhk** [syssi/xiaomi_airpurifier#289]

**Comment by IATkachenko** [comment]
@syssi, do you need any additional information/tests ?

**Comment by astenger** [comment]
I have the same issue.

from home assistant log details:

----------

Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:128
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 16:29:52 (1 occurrences)
Last logged: 16:29:52
Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsqs

----------

I had to set up the device in the Mi Home app in the Chinese mainland region (Australia did not work). The device is functional in the Mi Home app.

The device has a humidity and temperature sensor (accuracy is questionable when I compare the readings to other sensors in the same room)
The device supports the following modes in the Mi Home app:
- off
- low
- medium
- high
- humidity (target humidity between 40 and 70)

It also has the following options in the Mi Home app:
- scheduled on/off -> ...
- LED indicator light: on/off
- Notification sounds: on/off
![Screenshot 2022-12-04 at 14 37 22](https://user-images.githubusercontent.com/3413174/205478156-6e33b67d-fdef-41c7-a5c0-b67298f8c22b.png)

**Comment by astenger** [comment]
The temp sensor does not show up in the device view of the Mi Home app, but it does show in the room overview:
![IMG-6684](https://user-images.githubusercontent.com/3413174/205478302-6fd4ebd5-8d73-4df6-a82a-5c5287450d0e.PNG)

**Comment by astenger** [comment]
Update: installing the HACS version worked. Quite a bit of editing in the config files since I have two humidifiers in different rooms, but it does work. Thanks for making this work.

**Comment by syssi** [comment]
The device is supported by this custom component. Please give it a try!
