### ISSUE TITLE
Error: No module named 'miio.airfresh'

### ISSUE THREAD

**Issue by scythk** [syssi/xiaomi_airpurifier#290]
![image](https://user-images.githubusercontent.com/16112632/174803231-4a03d2a4-89be-4e47-8b54-623fec0d7da8.png)
The configuration file is as follow
![image](https://user-images.githubusercontent.com/16112632/174803251-0eceaf85-ca62-4cbd-8322-05e48818ae1a.png)

HA Version: 20220601.0 - latest
Home Assistant Core 2022.6.6

**Comment by tux2000** [comment]
I am running into the same problem after updating to HA version 2022.8.0 today. Was working fine with 2022.7 versions.

**Comment by syssi** [comment]
Please follow #292. I will close this one.
