### ISSUE TITLE
Integration not work

### ISSUE THREAD

**Issue by pticavorobey** [syssi/xiaomi_airpurifier#296]
Stable system after a scheduled reboot gives an error on all my humidifiers and air purifiers

`Platform error fan.xiaomi_miio_airpurifier - cannot import name 'DeviceInfo' from 'miio' (/usr/local/lib/python3.10/site-packages/miio/__init__.py)`

Reinstalling the component does not help

Home Assistant 2022.8.2
Supervisor 2022.07.0
Frontend 20220802.0 - latest

**Comment by syssi** [comment]
Could you check the errors carefully? Please provide the log again. I assume it's a new/another error.

**Comment by KrzysztofHajdamowicz** [comment]
> @KrzysztofHajdamowicz, look at it.

Sorry, my Python skills end here. STYJ02YM integration is abandoned for a few days and new maintainer will be welcomed!

**Comment by syssi** [comment]
Correct. If you start Home Assistant all `manifest.json` files are parsed and requirements are collected. Home Assistant uses `pip install` to install these requirements. It's not possible to install multiple versions of one library at the same time. At the moment `python-miio==0.5.11` of `miio2` wins the race and `xiaomi_miio_airpurifier` is unable to start because important packages of the `0.5.12` release are missing.

**Comment by syssi** [comment]
@KrzysztofHajdamowicz Do you still accept pull requests?

**Comment by KrzysztofHajdamowicz** [comment]
> @KrzysztofHajdamowicz Do you still accept pull requests?

Sure!

**Comment by syssi** [comment]
@pticavorobey I would provide some instructions how to manually edit/change the `miio2` component to be `python-miio==0.5.12` compatible. In best case the number of changes is pretty small. Are you able to edit the files of miio2 manually? As soon we know the required changes you or I can prepare a pull request.

**Comment by syssi** [comment]
Preparation:

1. We need a Home Assistant >=2022.8.0 instance.
2. Change `custom_components/miio2/manifest.json` to `python-miio==0.5.12`
3. Restart Home Assistant

Please provide all error the miio2 throws now.

**Comment by syssi** [comment]
This was easy. I would be happy if you could do the PR. If you don't know how to do it I can take over.

**Comment by syssi** [comment]
Do you use / did you fix the `nqkdev` version or the `KrzysztofHajdamowicz` fork?

**Comment by syssi** [comment]
If you see deprecation warning at your log you could apply these changes (locally) too:

https://github.com/nqkdev/home-assistant-vacuum-styj02ym/pull/56/files
