### ISSUE TITLE
Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq4

### ISSUE THREAD

**Issue by echupin** [syssi/xiaomi_airpurifier#298]
"Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq4"

This is an error when I don't specify the model in the configuration.
Model "deerma.humidifier.jsq4" cannot be specified.
If I specify the model "deerma.humidifier.jsq", the humidifier is not available in HA.

**Comment by baradetsky** [comment]
I also need this integration

**Comment by SandDeath** [comment]
join the request to add

**Comment by jejunpark** [comment]
I also need this integration

**Comment by Grawl** [comment]
https://github.com/syssi/xiaomi_airpurifier/issues/109

**Comment by syssi** [comment]
This is a duplicate of #109.
