### ISSUE TITLE
Initialization error.

### ISSUE THREAD

**Issue by bachulator** [syssi/xiaomi_airpurifier#3]
Hi,

Have an error during setup of the custom component:

Home Assistant
0.52.1
Hassio 1.0

Built using Python 3

ERROR (MainThread) [homeassistant.components.fan] Error while setting up platform xiaomi_airpurifier
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 164, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 352, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/config/custom_components/fan/xiaomi_airpurifier.py", line 55, in async_setup_platform
    from mirobo import AirPurifier, DeviceException
ImportError: cannot import name 'AirPurifier'

Let me know if you need any additional info.

**Comment by syssi** [comment]
Your python-mirobo library is too old. I assume you are using another component which requires an old version of python-mirobo. Please install this revision at least:

```
pip3 install "https://github.com/rytilahti/python-mirobo/archive/168f5c0ff381b3b02cedd0917597195b3c521a20.zip#python-mirobo"
```

**Comment by bachulator** [comment]
Not sure if this will work with Hassio version of Home Assistant. But, will check it later.

**Comment by syssi** [comment]
How did you install the component on Hassio?

**Comment by bachulator** [comment]
Just copied to custom_components under configuration directory, like it would be standard installation. P.S. Every other custom component works fine with this setup.

**Comment by syssi** [comment]
If you don't find a solution just wait a few weeks. I will update all home assistant components which requires python-mirobo to the latest library version. At the moment a development version of python-mirobo is needed (the release is outstanding). If there is a release it has to be introduced into home assistant. This needs some time. Your issue will be solved then.

**Comment by bachulator** [comment]
Cool. Thanks. Will wait for update then.

**Comment by bachulator** [comment]
Hi

I am back with new errors with new hassio/homeassistant release.

Home Assistant
0.53.0
Hassio 1.0

Built using Python 3
ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 381, in async_process_entity
    new_entity, self, update_before_add=update_before_add
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 210, in async_add_entity
    yield from entity.async_update()
  File "/config/custom_components/fan/xiaomi_airpurifier.py", line 191, in async_update
    ATTR_MOTOR_SPEED: state.motor_speed
  File "/usr/lib/python3.6/site-packages/mirobo/airpurifier.py", line 166, in motor_speed
    return self.data["motor1_speed"]
KeyError: 'motor1_speed'

**Comment by syssi** [comment]
I'm sorry. My changes wasn't merged yet and are not part of 0.53 unfortunately.

**Comment by syssi** [comment]
This PR needs to be merged to fix the issue: https://github.com/home-assistant/home-assistant/pull/9138

**Comment by bachulator** [comment]
That what I figured out, and that the reason I have deleted the report. Looking forward for the functionality though. Keep up the good work!

**Comment by syssi** [comment]
With the release of HA 0.54 the issue should be solved.

**Comment by bachulator** [comment]
Hi syssi. I have updated HA to 0.54 and found that component work really well. The only small issue the icon of the air purifier doesn't change the color when the device is active. 
Thanks.

**Comment by syssi** [comment]
You are right. Could you please open a new issue?
