### ISSUE TITLE
Unsupported device found: deerma.humidifier.jsq5

### ISSUE THREAD

**Issue by josephfh** [syssi/xiaomi_airpurifier#303]
deerma.humidifier.jsq5

**Comment by wilotas** [comment]
Same here. New Air Humidifier 2.

**Comment by wilotas** [comment]
Going over documentation...this model should be recognized because it is supported under specs, isn´t it?

**Comment by syssi** [comment]
There is some confusion because this custom component supports some more devices compared to the official `xiaomi_miio` component. The HA core doesn't support the `jsq5`. This component does support the `jsq5`.

**Comment by steveof2620** [comment]
Same issue here. The integration finds it and sets it up but fails to setup. Should I be using something else?

**Comment by elminos** [comment]
> deerma.humidifier.jsq5

Same here! I'll try the "fan" workaround.

**Comment by foreignmeloman** [comment]
@steveof2620 Thanks for the tip, changing the entry to `fan` did help and the humidifier appeared in the dashboard, but for some reason there are only two types of controls: on/off switch and mode selector:
![image](https://user-images.githubusercontent.com/11769352/198151340-8ef64109-c31e-44a1-9e3d-384e36502a53.png)
I know from the Mi Home app you can control the `Buzzer`, `Target humidity` and `Led` settings, but here they only appear as attributes. How can I add the missing controls?

**Comment by steveof2620** [comment]
You will most likely need to add those via template sensors referencing the device attributes. Instructions are in the documentation. 

https://github.com/syssi/xiaomi_airpurifier

**Comment by syssi** [comment]
Please try this custom component using HACS. The model is supported here. It's just not supported of the official HA core component.
