### ISSUE TITLE
Unsupported device deerma.humidifier.jsq5

### ISSUE THREAD

**Issue by kirillisprk** [syssi/xiaomi_airpurifier#307]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:128 
Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

**Comment by syssi** [comment]
Duplicate #311
