### ISSUE TITLE
Unsupported device found! deerma.humidifier.jsq2w

### ISSUE THREAD

**Issue by GedasBu** [syssi/xiaomi_airpurifier#309]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:128
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 19:23:27 (1 occurrences)
Last logged: 19:23:27

**Comment by syssi** [comment]
Duplicate #315
