### ISSUE TITLE
Support for device zhimi.airpurifier.v7

### ISSUE THREAD

**Issue by SebuZet** [syssi/xiaomi_airpurifier#31]
Hi Everyone,

At the beginning I would like to thank you for great work. I finally got the toke, what was really hard, and I found new problem: "Unsupported device found". Is it possible to add support for Xiaomi Air Purifier Pro 2018 (model: zhimi.airpurifier.v7)?

Bellow you can find log from info method:
{'result': {'life': 1761, 'cfg_time': 0, 'token': 'HIDEN', 'mac': HIDEN, 'fw_ver': '1.4.3_19105', 'hw_ver': 'MW300', 'uid': 1900358663, 'model': 'zhimi.airpurifier.v7', 'wifi_fw_ver': 'SD878x-14.76.36.p84-702.1.0-WM', 'ap': {'rssi': -51, 'ssid': 'HIDEN', 'bssid': 'HIDEN'}, 'netif': {'localIp': 'HIDEN', 'mask': '255.255.255.0', 'gw': 'HIDEN', 'gw_mac': 'HIDEN'}, 'mmfree': 134204, 'ot': 'ott', 'otu_stat': [0, 0, 0, 0, 0, 27], 'ott_stat': [1, 0, 14, 201]}, 'id': 1}

Thanks in advance :)

**Comment by syssi** [comment]
Please checkout the custom component and give it a try! I don't know the supported features of the V7 right now. I hope you can help to get the device supported.

**Comment by SebuZet** [comment]
I'm already using custom component from this repo. I believe that this device should be very similar to version 6. I'll help getting this to work - just let me know how can I help. One thing I can say now: getting working token is not easy.

**Comment by SebuZet** [comment]
Ok, I just noticed that I'm using "xiaomi_miio_fan" instead of "xiaomi_miio". I'll check that after work.

**Comment by SebuZet** [comment]
Apologize, it was my mistake. I've used wrong component. My HA instance can connect to purifier without problems.

**Comment by syssi** [comment]
You've a new revision of the device nevertheless. Could you provide a screenshot of the Home Assistant card? I'm interested in the different values of the attributes (and want to know which attribute are "null").

**Comment by syssi** [comment]
![airpurifier](https://user-images.githubusercontent.com/2735933/50221221-c106c400-0394-11e9-9764-530a26085314.png)

**Comment by SebuZet** [comment]
I'm new in HA. I've started playing with HA few days ago. 
What should i do to have such card? Should such card be added automatically? Till now i've added few sensors using sensor.template.
I can provide more info later when i'll be back at home.

**Comment by syssi** [comment]
If you haven't customized your Home Screen there should be a fan entity. If you click on the entity this info card appears. If you cannot find the card a screenshot of your dev-state page would contains the same information's I'm interested in.

**Comment by syssi** [comment]
Perfect! Thanks a lot!

**Comment by SebuZet** [comment]
Hello,

It works perfect for my. 
Just keep in mind that for changing the speed you have to change mode to „favorite”.
I am using automation rules in HA and everything’s works as expected.
I’ve adopted automations scripts from this thread https://community.home-assistant.io/t/automating-air-purifiers/81745/6 <https://community.home-assistant.io/t/automating-air-purifiers/81745/6>

BR,
Sebu

**Comment by syssi** [comment]
Could somebody upate/use/test this custom component and provide a screenshot again? I've improved the V7 support. The attributes without values ("-") are removed now. I've added some addition properties/attributes for testing. Does it provide some values?

**Comment by Mazon** [comment]
<img width="365" alt="screen shot 2019-01-14 at 14 52 25" src="https://user-images.githubusercontent.com/59775/51101229-5ff3d400-180c-11e9-9e9a-ea999279d123.png">

Thanks man!

**Comment by Mazon** [comment]
You want me to test something?

**Comment by syssi** [comment]
Could you test the "set volume service"? Does it update the attribute/property "volume" of the card?

**Comment by SebuZet** [comment]
I will check this service today evening.

**Comment by syssi** [comment]
Cool! Thanks for your support!

**Comment by Mazon** [comment]
<img width="367" alt="screen shot 2019-01-14 at 15 08 26" src="https://user-images.githubusercontent.com/59775/51101705-4f445d80-180e-11e9-9d86-a512f10ef9ea.png">

Seems nice!

**Comment by SebuZet** [comment]
This is screenshot from my system but property will be checked evening

**Comment by SebuZet** [comment]
I've checked this service and it is working correctly. After calling the service with param 33 device card was updated with new value. I've no idea what is the meaning /purpose of this parameter :)

**Comment by syssi** [comment]
It should be the sound volume of some (beep?) sounds.

**Comment by SebuZet** [comment]
Ok, so it works. Thanks again. 

ps. „fan.xiaomi_miio_set_led_brightness” doesn’t work

**Comment by syssi** [comment]
Are you able to control the led brightness with the MiHome app? As far as I know the Airpurifier Pro doesn't support led brightness. The LED can be turned on and off only.

**Comment by SebuZet** [comment]
No, there is no such possibilities in MiHome App. Air purifier dims LED display automaticaly according to ambient light level. I thought that this behaviuor can be controlled via this service.
Thanks again
