### ISSUE TITLE
Unsupported Device: zhimi.airp.mb5a

### ISSUE THREAD

**Issue by eric-keur** [syssi/xiaomi_airpurifier#310]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:128
Integration: Xiaomi Miio (documentation, issues)
First occurred: 8:22:11 PM (1 occurrences)
Last logged: 8:22:11 PM

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: zhimi.airp.mb5a

**Comment by syssi** [comment]
Duplicate of #301.
