### ISSUE TITLE
Unsupported Device: deerma.humidifier.jsq5

### ISSUE THREAD

**Issue by RonL1** [syssi/xiaomi_airpurifier#311]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:128
Integration: Xiaomi Miio (documentation, issues)
First occurred: 22:47:53 (1 occurrences)
Last logged: 22:47:53

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

**Comment by alexanderek** [comment]
same issue

**Comment by mrbig00** [comment]
same issue

**Comment by ciganskovic** [comment]
me too @syssi let me know if i can help by providing data.

**Comment by le-clu** [comment]
same issue

**Comment by erdose** [comment]
Same issue

**Comment by epiespen** [comment]
Yes, mii too, so to speak.

**Comment by zverek06** [comment]
Same issue

**Comment by engusz** [comment]
Same issue here. @syssi , how can we help detect the error?

![image](https://user-images.githubusercontent.com/26418215/206907179-926bc17c-3058-4f3a-a54e-cffd2e6ed454.png)

![image](https://user-images.githubusercontent.com/26418215/206907252-13065edb-b833-4c87-8622-8c64dd0aa23e.png)

![image](https://user-images.githubusercontent.com/26418215/206907350-f07b1c35-026f-49e0-ac50-07d828c2ece3.png)

**Comment by Aanistratenko1984** [comment]
i have same issue

**Comment by syssi** [comment]
If you install the custom component (`xiaomi_miio_airpurifier`) of this repository the device should be supported. It's not supported by the official component (`xiaomi_miio`) of the HA core.

**Comment by wuschel1337** [comment]
Same error for me

**Comment by davpro7** [comment]
Same here:
https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

**Comment by SergDevHA** [comment]
The same issue for me

**Comment by syssi** [comment]
The device is supported if you use this custom component instead of the official component. Please give it a try!
