### ISSUE TITLE
Unsupported device zhimi.airp.mb5a

### ISSUE THREAD

**Issue by M5M400** [syssi/xiaomi_airpurifier#312]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:128
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 4:48:49 PM (1 occurrences)
Last logged: 4:48:49 PM
Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: zhimi.airp.mb5a

**Comment by wehrstedt** [comment]
Same for me. Its a Xiaomi Smart Air Purifier 4

**Comment by nelsontyc** [comment]
having same issue as well!

**Comment by syssi** [comment]
Duplicate #310
