### ISSUE TITLE
Unsupported device found! deerma.humidifier.jsq2w

### ISSUE THREAD

**Issue by BlueheIix** [syssi/xiaomi_airpurifier#315]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:128
Integration: Xiaomi Miio

**Comment by ShammanIT** [comment]
Try to add it like   
model: deerma.humidifier.jsq3 
It work correctly.
![Screenshot_2022-12-11-09-30-09-330-edit_com yandex browser](https://user-images.githubusercontent.com/80038299/206886502-ad3ccb2a-2e04-46bb-8c74-307abf505196.jpg)

**Comment by MrFlsee** [comment]
same issue

**Comment by liwenjie119** [comment]
same error ： deerma.humidifier.jsq2g

**Comment by gaspoza** [comment]
Same issue when adding Xiaomi Smart Humidifier 2

**Comment by Trainee14BGE** [comment]
Same issue

**Comment by Green-Kite** [comment]
Same issue

**Comment by jviha** [comment]
Same...

**Comment by netsensation** [comment]
Same issue

**Comment by gappie** [comment]
Is it possible to integrate this unit?

**Comment by gappie** [comment]
You can use the following HACS repo until it is supported here:
https://github.com/al-one/hass-xiaomi-miot

**Comment by syssi** [comment]
Please try this custom component using HACS. The model is supported here. It's just not supported of the official HA core component.
