### ISSUE TITLE
Not supported device error: deerma.humidifier.jsq5

### ISSUE THREAD

**Issue by JGH88** [syssi/xiaomi_airpurifier#319]
2023-01-11 09:15:35.449 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

**Comment by cavazzini-8v** [comment]
Same error, with Home Assistant 2023.1.2

**Comment by bsoter** [comment]
Same error here 2022.12.8

**Comment by tomasr1981** [comment]
Same error Home Assistant 2023.1.4

**Comment by vyshy** [comment]
Same error Home Assistant 2023.1.5. Waiting...

**Comment by julianbl** [comment]
NAME:     Mi Smart Antibacterial Humidifier
   ID:       454469761
   MAC:      B4:60:ED:4A:D0:95
   MODEL:    deerma.humidifier.jsq5

**Comment by prophetmaster** [comment]
same error please add

**Comment by JGH88** [comment]
No response from Xiaomi or this GitHub page yet.

**Comment by syssi** [comment]
The device is supported if you use this custom component instead of the official component. Please give it a try!

**Comment by syssi** [comment]
Duplicate #311

**Comment by JGH88** [comment]
Thank you so much :-) It works now with the integration from HACS.It is strange that the humidifier is on the list of compatible devices. Den 28. jan. 2023 kl. 21.17 skrev Sebastian Muszynski ***@***.***>:﻿
The device is supported if you use this custom component instead of the official component. Please give it a try!

**Comment by bsoter** [comment]
Hi All can you please send me the configuration yaml with all available entities for deerma.humidifier.jsq5 mine connected via HACS but only I see/add the on/off switch for the product. Please help if you have fully working template, Thanks
