### ISSUE TITLE
Unsupported device found! deerma.humidifier.jsq2w

### ISSUE THREAD

**Issue by 42ska** [syssi/xiaomi_airpurifier#321]
Уровень: ОШИБКА
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:128
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 12 января 2023 г., 17:01:20 (1 occurrences)
Last logged: 12 января 2023 г., 17:01:20

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2w

**Comment by watak** [comment]
Sme error: 

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2w

**Comment by syssi** [comment]
Duplicate #315
