### ISSUE TITLE
Unsupported device found!

### ISSUE THREAD

**Issue by miladak** [syssi/xiaomi_airpurifier#324]
I ordered a Xiaomi Smart Humidifier 2 ( deerma.humidifier.jsq2w) and wanted to add the device to Home assistant, but I keep getting a message that the device is not supported. I've seen that there are many issues regarding this. My question is, will the device get support from you in the future or should I return the device?

**Comment by belerovon** [comment]
Same for Xiaomi Smart Antibacterial Humidifier

**Comment by syssi** [comment]
Please try this custom component using HACS. The model is supported here. It's just not supported of the official HA core component.
