### ISSUE TITLE
Unable to integrate Xiaomi Smart Humidifier 2

### ISSUE THREAD

**Issue by liviustancu** [syssi/xiaomi_airpurifier#327]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:129
Integration: Xiaomi Miio (documentation, issues)
First occurred: 15:25:25 (1 occurrences)
Last logged: 15:25:25

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2w

**Comment by gappie** [comment]
You can use the following HACS repo until it is supported here:
https://github.com/al-one/hass-xiaomi-miot

**Comment by sim186** [comment]
I also have the same humidifier (Model: deerma.humidifier.jsq2w), I used the the _deerma.humidifier.jsq3_ doesn't look fully supported but at least I can switch on and off and change the mode, for me is enough.

**Comment by rebelchris** [comment]
@sim186 How did you change the model from `jsq2w` to `jsq3` not quite sure where to overwrite it.

**Comment by PedroSilv4** [comment]
> You can use the following HACS repo until it is supported here: https://github.com/al-one/hass-xiaomi-miot

Its supported worked there 🙏

**Comment by syssi** [comment]
Please try this custom component using HACS. The model is supported here. It's just not supported of the official HA core component.
