### ISSUE TITLE
Unsupported Device: deerma.humidifier.jsq2w

### ISSUE THREAD

**Issue by Kiarant** [syssi/xiaomi_airpurifier#330]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:130
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 23:24:43 (1 occurrences)
Last logged: 23:24:43

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2w

**Comment by PedroSilv4** [comment]
https://github.com/al-one/hass-xiaomi-miot

**Comment by syssi** [comment]
Please try this custom component using HACS. The model is supported here. It's just not supported of the official HA core component.
