### ISSUE TITLE
deerma.humidifier.jsq5

### ISSUE THREAD

**Issue by AlbCod** [syssi/xiaomi_airpurifier#331]
HI, as recommended I open a new issue.
Alb

Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:130
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 09:33:37 (1 occurrences)
Last logged: 09:33:37
Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

**Comment by Krzysztonek** [comment]
Hi,
Same issue here:

Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:130
Integration: Xiaomi Miio (documentation, issues)
First occurred: 13:23:15 (3 occurrences)
Last logged: 13:25:03

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

**Comment by EkzikP** [comment]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:130
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 09:14:52 (1 occurrences)
Last logged: 09:14:52

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

**Comment by OHCM** [comment]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:129
Integration: Xiaomi Miio (documentation, issues)
First occurred: 06:19:14 (4 occurrences)
Last logged: 14:14:01

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2w

**Comment by ha-new** [comment]
Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

**Comment by Blazon10** [comment]
Hi, same here

Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:128
Integration: Xiaomi Miio (documentation, issues)
First occurred: 2023. április 22. 15:52:55 (3 occurrences)
Last logged: 13:35:40

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

**Comment by vogonwann** [comment]
Same here `deerma.humidifier.jsq5`

**Comment by syssi** [comment]
Please try this custom component using HACS. The model is supported here. It's just not supported of the official HA core component.
