### ISSUE TITLE
 homeassistant.components.xiaomi_miio unsupported device deerma.humidifier.jsq2w

### ISSUE THREAD

**Issue by OHCM** [syssi/xiaomi_airpurifier#333]
Home Assistant integration fails for Xiaomi Smart Humidifier 2

**Comment by lindstrm** [comment]
Was about to post this one as well.

**Comment by rebelchris** [comment]
Also happening for me on the Xiaomi Smart Humidifier 2 `deerma.humidifier.jsq2w`

**Comment by Hernersi** [comment]
Same issue here deerma.humidifier.jsq2w does not work "unsupported device"

**Comment by kchlosta** [comment]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:130
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 18 kwietnia 2023 20:46:08 (1 occurrences)
Last logged: 18 kwietnia 2023 20:46:08
Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2w

**Comment by syssi** [comment]
Please try this custom component using HACS. The model is supported here. It's just not supported of the official HA core component.
