### ISSUE TITLE
Please add support to zhimi.airp.mb5a

### ISSUE THREAD

**Issue by uhwf91p** [syssi/xiaomi_airpurifier#336]
I've tried to connect my new air purifier to homeassistant and got the following error:
ERROR (MainThread) [homeassistant.components.xiaomi_miio] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: zhimi.airp.mb5a
Could you please add support for it?

**Comment by cerritus55** [comment]
I have the same problem

> 2023-07-29 10:43:31.334 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: zhimi.airp.mb5a
> 
Any chance this getting support?

**Comment by VanQz** [comment]
Have this issue too. Please add support for this thanks!

**Comment by wlucha** [comment]
Same issue here, please add support

**Comment by phbasler** [comment]
Because I didn't want to wait:
I had great success with the python api of the main branch https://github.com/rytilahti/python-miio.git . Using the device factory it was easy writing up a python script for the stuff I wanted to control.
To connect the script to HA you can use MQTT

**Comment by cerritus55** [comment]
I also It also didn’t want to wait. I had a great success with an HACS repo, works for me just fine.
https://github.com/al-one/hass-xiaomi-miot

**Comment by p2bauer** [comment]
Looks like I'll also go for the HACS repo above that @cerritus55 mentioned - but wanted to keep this issue alive since it would be great to be supported with the core integration! :-)

**Comment by MisiekG** [comment]
I have the same problem, please add integration.

**Comment by syssi** [comment]
Duplicate of #301
