### ISSUE TITLE
Please add support to deerma.humidifier.jsq2g

### ISSUE THREAD

**Issue by wngweiping** [syssi/xiaomi_airpurifier#339]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:130
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 21:44:17 (2 occurrences)
Last logged: 21:52:40

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2g

**Comment by AlexzeyK** [comment]
Hi guys.
I also bought this device. I also received an unsupported device.

Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:130
Integration: Xiaomi Miio (documentation, issues)
First occurred: 4 червня 2023 р. о 22:34:49 (1 occurrences)
Last logged: 4 червня 2023 р. о 22:34:49

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2g

It is now being actively sold. Please add support for this device.

**Comment by adriannowak** [comment]
Up with `deerma.humidifier.jsq2w`

**Comment by LeChat109** [comment]
up

**Comment by leandrofranca** [comment]
Up

**Comment by nilsi** [comment]
Same here, would also love if this was supported!

**Comment by AlexzeyK** [comment]
I already have 4 such devices. 
Now I use HACS. But we really need direct support from HA!

**Comment by DmitryL0** [comment]
Up

**Comment by wolfich** [comment]
up!

**Comment by Hedin9000** [comment]
deerma.humidifier.jsq2g
Xiaomi Smart Humidifier 2 (MJJSQ05DY)

**Comment by alexandersaulenko** [comment]
up!

**Comment by DmitryL0** [comment]
Up

**Comment by mrmuro** [comment]
Up

**Comment by fralloger** [comment]
up!

**Comment by RhavoX** [comment]
Up

**Comment by QAstron** [comment]
Up

**Comment by grandead** [comment]
Up

**Comment by Zalmat** [comment]
Up

**Comment by cydwg** [comment]
Up, also have the same issue

**Comment by syssi** [comment]
Duplicate of #306
