### ISSUE TITLE
Unsupported device: deerma.humidifier.jsq2w

### ISSUE THREAD

**Issue by tzrkgit** [syssi/xiaomi_airpurifier#345]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:135
Integration: Xiaomi Miio ([documentation](https://www.home-assistant.io/integrations/xiaomi_miio), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+xiaomi_miio%22))
First occurred: 5:40:31 PM (2 occurrences)
Last logged: 5:42:10 PM

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2w

**Comment by msth** [comment]
same problem here

**Comment by trancer86** [comment]
Please add support :-(

Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:162
Integration: Xiaomi Miio (documentation, issues)
First occurred: 19:19:30 ч. (1 occurrences)
Last logged: 19:19:30 ч.

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2w

**Comment by kajarit** [comment]
same here

**Comment by jsole** [comment]
Same error, please add support.

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2w

**Comment by SoloMen88** [comment]
Hello, I also bought such a humidifier and it is not supported by the integration, the log says: '2023-12-14 18:42:23.472 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2g'.
Please add support, for my part I am ready to send the necessary data and participate in testing.

**Comment by kajarit** [comment]
It works with this integration:

https://github.com/al-one/hass-xiaomi-miot

**Comment by trancer86** [comment]
> It works with this integration:
> 
> https://github.com/al-one/hass-xiaomi-miot

I also succeeded with the HACS integration "Xiaomi Miio Auto"
![Screenshot_2023-12-14-18-50-06-043_io homeassistant companion android](https://github.com/syssi/xiaomi_airpurifier/assets/89747460/5f7b4a1d-e8f3-47bf-88e6-b78dfc1e884f)

**Comment by SoloMen88** [comment]
Thank you very much, everything started up, I got confused in the additions!

**Comment by n3on4s** [comment]
Also need integration here :)  <3

**Comment by redimer2** [comment]
Also need integration 
Home Assistant Core
`2024-01-27 22:24:00.433 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2w`

**Comment by XaMeJleoH** [comment]
Plus, the same problem

**Comment by syssi** [comment]
Please try this custom component using HACS. The model is supported here. It's just not supported of the official HA core component.
