### ISSUE TITLE
Air Humidifier CA4 (zhimi.humidifier.ca4) configuration

### ISSUE THREAD

**Issue by DimChik2903** [syssi/xiaomi_airpurifier#346]
Does anyone have a ready-made configuration for Air Humidifier CA4 (zhimi.humidifier.ca4)? An example that I found for Air Humidifier CA1 (zhimi.humidifier.ca1) is not fully suitable

**Comment by vladshundalov** [comment]
I did recently for my CA4

**Comment by syssi** [comment]
It's supported by this custom component. Please give it a try!
