### ISSUE TITLE
Please add support :-(

### ISSUE THREAD

**Issue by trancer86** [syssi/xiaomi_airpurifier#351]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:162
Integration: Xiaomi Miio (documentation, issues)
First occurred: 19:19:30 ч. (1 occurrences)
Last logged: 19:19:30 ч.

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2w

**Comment by syssi** [comment]
Please try this custom component using HACS. The model is supported here. It's just not supported of the official HA core component.
