### ISSUE TITLE
Please add support :((

### ISSUE THREAD

**Issue by akovovh** [syssi/xiaomi_airpurifier#353]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:162
Integration: Xiaomi Miio (documentation, issues)
First occurred: 21:57:54 (1 occurrences)
Last logged: 21:57:54

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

**Comment by syssi** [comment]
Please install this custom component using HACS instead of the official one. The device is supported here.
