### ISSUE TITLE
New device

### ISSUE THREAD

**Issue by baizan1** [syssi/xiaomi_airpurifier#36]
I have a mijia humidifier not recognize: deerma.humidifier.mjjsq. It is this device: https://es.aliexpress.com/item/4000047972849.html

**Comment by tehnoinstyle** [comment]
I also have such a humidifier (deerma.humidifier.mjjsq). But I could not add it to the hass.io.

I get the following error:

`2019-11-28 22:19:43 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for xiaomi_miio which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-11-28 22:19:43 ERROR (MainThread) [custom_components.fan.fan] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.mjjsq`

How do I add it to hass.io? Thanks.

**Comment by syssi** [comment]
It's supported now.

**Comment by tehnoinstyle** [comment]
Hello.
What do I need to do? I am ready to try.

**Comment by syssi** [comment]
I'm cleaning up the issues only. A release of python-miio is still required first.

**Comment by tehnoinstyle** [comment]
understand.
