### ISSUE TITLE
Please add deerma.humidifier.jsq2w

### ISSUE THREAD

**Issue by PalmTamino** [syssi/xiaomi_airpurifier#361]

**Comment by Shagbark** [comment]
Vote

**Comment by mspaehn** [comment]
+1

**Comment by panichev-sa** [comment]
+1

**Comment by tanchu** [comment]
+1

**Comment by smkrv** [comment]
+1

**Comment by kristofgyuracz** [comment]
https://github.com/syssi/xiaomi_airpurifier/pull/352 Added it here, you can use the changes locally until it's merged if you'd like.

**Comment by duanemck** [comment]
> > #352 Added it here, you can use the changes locally until it's merged if you'd like.
> 
> This removes possible errors. However, it does not provide access to the necessary functionality. Personally, I am most interested in the water level, or rather the sensor for its absence.

I'm not a Python dev, so could be wrong here, but from what I can see, the jsq2w is now looped in with the *JSQS models, and those support the following attributes (including `no water` and `tank removed`)

https://github.com/syssi/xiaomi_airpurifier/blob/develop/custom_components/xiaomi_miio_airpurifier/fan.py#L1966

![image](https://github.com/syssi/xiaomi_airpurifier/assets/429394/e2abb7c0-b865-426b-8379-9d5a53a8eed9)

![image](https://github.com/syssi/xiaomi_airpurifier/assets/429394/6ff70158-15ee-4dd4-9e36-50363ee83264)

Will need to test this version or wait for it to make it to the core HA to confirm.

**Comment by AndriiAdamets** [comment]
+1

**Comment by kristofgyuracz** [comment]
> > > #352 Added it here, you can use the changes locally until it's merged if you'd like.
> > 
> > 
> > This removes possible errors. However, it does not provide access to the necessary functionality. Personally, I am most interested in the water level, or rather the sensor for its absence.
> 
> I'm not a Python dev, so could be wrong here, but from what I can see, the jsq2w is now looped in with the *JSQS models, and those support the following attributes (including `no water` and `tank removed`)
> 
> https://github.com/syssi/xiaomi_airpurifier/blob/develop/custom_components/xiaomi_miio_airpurifier/fan.py#L1966
> 
> ![image](https://private-user-images.githubusercontent.com/429394/310836608-e2abb7c0-b865-426b-8379-9d5a53a8eed9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NzQyOTcsIm5iZiI6MTcxMDc3Mzk5NywicGF0aCI6Ii80MjkzOTQvMzEwODM2NjA4LWUyYWJiN2MwLWI4NjUtNDI2Yi04Mzc5LTlkNWE1M2E4ZWVkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxNDU5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjNmYWVkZWU4ZjM1MWQzYmM4YWEyMWQ3ZjNlZmVhYzVlY2QxNjA2NjJiNzNhYTE5NmJiODNmZDhkMTM0ZTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XowMZ5HGWhrjQxd1Vr6pI4KAGxn8h9z5mpdO3IWt6gM)
> 
> ![image](https://private-user-images.githubusercontent.com/429394/310835830-6ff70158-15ee-4dd4-9e36-50363ee83264.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NzQyOTcsIm5iZiI6MTcxMDc3Mzk5NywicGF0aCI6Ii80MjkzOTQvMzEwODM1ODMwLTZmZjcwMTU4LTE1ZWUtNGRkNC05ZTM2LTUwMzYzZWU4MzI2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxNDU5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDk0ODY0NzIwYjkyM2VlYmNlMWQ3NGU3MmJhZGY1ZjU3YjMyY2YwMjI2NTZkYzg0MDg4YWIxMDg0MWMxYTE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vapXmfQUF4DdNiApm2WD2dPJ_tV7Rm-z3h8afXrBqEc)
> 
> Will need to test this version or wait for it to make it to the core HA to confirm.

Hi, thanks for pointing out the issue. Didn't have time to check it with handling it as a jsqs model, and the PR was merged since. Will test in anyways, and submit if it works.

**Comment by smkrv** [comment]
+1

**Comment by Rishal92** [comment]
+1 

I also would like to get support added for this device

**Comment by syssi** [comment]
Please try this custom component using HACS. The model is supported here. It's just not supported of the official HA core component.
