### ISSUE TITLE
Add zhimi.airp.mb5a support

### ISSUE THREAD

**Issue by MuzzaGuzzaBuzza** [syssi/xiaomi_airpurifier#363]
Greetings

Trying to add Xiaomi Air Purifier 4, but it looks like this particular model/edition isn't yet supported: zhimi.airp.mb5a. Two other Air Purifier 4s I have are zhimi.airp.mb5 and they have integrated perfectly into HA.

Any chance of an update to include this model?

Many thanks

**Comment by OB1KOB** [comment]
I think here the same problem Xiaomi Air Purifier 4

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: zhimi.airp.mb5a

**Comment by filipkotoucek** [comment]
+1 same here. I have HASS in docker lscr.io/linuxserver/homeassistant latest 379fd0081054. Would this model be supprted anytime?

**Comment by syssi** [comment]
Duplicate of #301
