### ISSUE TITLE
Unsupported device found! deerma.humidifier.jsq5 does'nt work.

### ISSUE THREAD

**Issue by zsgodor** [syssi/xiaomi_airpurifier#365]
Napló: homeassistant.components.xiaomi_miio
Forrás: components/xiaomi_miio/__init__.py:162
integráció: Xiaomi Miio (dokumentáció, problémák)
Először fordult elő: du. 2:59:18 (2 Események)
Utoljára naplózott: du. 3:35:53

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

**Comment by Smandurlo** [comment]
+1 same device

**Comment by Hackbard** [comment]
+1

Logger: homeassistant.components.xiaomi_miio
Quelle: components/xiaomi_miio/__init__.py:162
Integration: Xiaomi Miio (Dokumentation, Probleme)
Erstmals aufgetreten: 10:43:04 (2 Vorkommnisse)
Zuletzt protokolliert: 10:46:44

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5
![Uploading PXL_20240725_084554589.jpg…]()

**Comment by Krzysztonek** [comment]
Same issue here with the same device:

Log details **(ERROR)**
```
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:162
integration: Xiaomi Miio (documentation, issues)
First occurred: 04:37:05 (2 occurrences)
Last logged: 04:37:30

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues
and provide the following data: deerma.humidifier.jsq5
```
Core 2024.8.0
Supervisor 2024.08.0
Operating System 12.4
Frontend 20240806.1

**Comment by syssi** [comment]
Please try this custom component using HACS. The model is supported here. It's just not supported of the official HA core component.
