### ISSUE TITLE
Unsupported device found! deerma.humidifier.jsq2w

### ISSUE THREAD

**Issue by JuMalIO** [syssi/xiaomi_airpurifier#366]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:162
integration: Xiaomi Miio (documentation, issues)

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq2w

**Comment by JuMalIO** [comment]
I assume this will fix it?
https://github.com/syssi/xiaomi_airpurifier/commit/f22c2c035c416f33ca3de8eb765dd4b42977e8cf
can you release it?

**Comment by jobsidi** [comment]
im getting "Unable to find mapping for deerma.humidifier.jsq2w, falling back to deerma.humidifier.jsqs     " error anyway

**Comment by DooMMasteR** [comment]
For me it is not working at all currently, which is a bit weird since it had worked in the past....

**Comment by septarchy** [comment]
It doesn't work for me also. Would love to use it somehow to automate my humidity indoors because of ac.

**Comment by syssi** [comment]
Please try this custom component using HACS. The model is supported here. It's just not supported of the official HA core component.
