### ISSUE TITLE
Add new device deerma.humidifier.jsq5

### ISSUE THREAD

**Issue by Partizanin** [syssi/xiaomi_airpurifier#373]
Logger: homeassistant.components.xiaomi_miio
Source: components/xiaomi_miio/__init__.py:162
integration: Xiaomi Miio (documentation, issues)
First occurred: 10:28:28 (1 occurrences)
Last logged: 10:28:28

Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.jsq5

**Comment by syssi** [comment]
Please use this custom component instead of the official one: https://github.com/syssi/xiaomi_airpurifier
