### ISSUE TITLE
Add support for zhimi.airpurifier.ma4

### ISSUE THREAD

**Issue by Nizm0** [syssi/xiaomi_airpurifier#39]
Hi
I bought recently the newest air purifier Xiaomi Air Purifier 3 and it is recognized as model zhimi.airpurifier.ma4, HA i received error {'code': -5001, 'message': 'command error'}
Unfortunately i do not know how to add some more information.

**Comment by mouth4war** [comment]
So, the parent miio library is still in the process of adding support. Seems people have tested the open PR there and it works so @syssi  can add support for miot purifiers in HA soon.

**Comment by syssi** [comment]
The device is supported now.
