### ISSUE TITLE
Model deerma.humidifier.mjjsq can not be recognized 

### ISSUE THREAD

**Issue by xia0linz1** [syssi/xiaomi_airpurifier#43]
Model deerma.humidifier.mjjsq has been define in fan.py,  but will never been recognized during platform initializing ( fan.py line 583 to 637 ).

**Comment by syssi** [comment]
Please update the custom component and give it another try.

**Comment by xia0linz1** [comment]
Download the latest xiaomi_miio_airpurifier from branch develop, and the ERROR remain. 
Got error :
Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.mjjsq

The configuration.yaml like:
`fan:
  - platform: xiaomi_miio_airpurifier
    host: 192.168.1.61
    token: e24*************de923eb9e024
    model: deerma.humidifier.mjjsq
`
I think the porblem locates at fan.py line 583 to 637, model deerma.humidifier.mjjsq will never match any if condition.

**Comment by anhnvme** [comment]
> Download the latest xiaomi_miio_airpurifier from branch develop, and the ERROR remain.
> Got error :
> Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.mjjsq
> 
> The configuration.yaml like:
> `fan:
> 
> * platform: xiaomi_miio_airpurifier
>   host: 192.168.1.61
>   token: e24*************de923eb9e024
>   model: deerma.humidifier.mjjsq
>   `
>   I think the porblem locates at fan.py line 583 to 637, model deerma.humidifier.mjjsq will never match any if condition.

same issue +1

**Comment by syssi** [comment]
Fixed! Please try again.
