### ISSUE TITLE
Add support for Xiaomi Mijia Smart Sterilization Humidifier (SCK0A45)

### ISSUE THREAD

**Issue by jduvesnu** [syssi/xiaomi_airpurifier#45]
Hello, I've got Xiaomi Mijia Smart Sterilization Humidifier (SCK0A45). Can't get it work with Home Assistant 0.103.5. Could you help me please? Thank you!

**Comment by syssi** [comment]
Could you provide the model name of the device?

**Comment by jduvesnu** [comment]
model is SCKOA45

**Comment by syssi** [comment]
If you add the xiaomi_airpurifier component to HA, which error message do you see (at the log)? This error contains the model name I'm asking for.

**Comment by jduvesnu** [comment]
Уровень: ERROR
Thu Jan 02 2020 21:45:28 GMT+0300 (Москва, стандартное время)
Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: deerma.humidifier.mjjsq


My device: 
https://s.click.aliexpress.com/e/b6xEBOaI

**Comment by syssi** [comment]
Could you post the section of your configuration.yaml? Are you sure you are using this custom component already?

**Comment by jduvesnu** [comment]
not sure. i'm using this code to add the device
fan:
   - platform: xiaomi_miio
     host: 192.168.88.214
     token: de1ba2c12f6149922d9b88109f193110

**Comment by syssi** [comment]
The platform must be called `xiaomi_miio_airpurifier` and the files of this repository must be copied to your custom components directory.

**Comment by jduvesnu** [comment]
configuration.yaml

fan:
   - platform: xiaomi_miio_airpurifier
     name: Xiaomi Air Humidifier
     host: 192.168.88.214
     token: de1ba2c12f6149922d9b88109f193110
    


log

Platform error: fan - Requirements for xiaomi_miio_airpurifier not found: ['python-miio>=0.4.8'].


You are using a custom integration for xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.


2020-01-02 22:30:24 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.


2020-01-02 22:34:11 ERROR (MainThread) [homeassistant.config] Platform error: fan - Requirements for xiaomi_miio_airpurifier not found: ['python-miio>=0.4.8'].

**Comment by syssi** [comment]
Please update HA to the development version.

**Comment by jduvesnu** [comment]
How I can do it?

**Comment by jduvesnu** [comment]
I got it!!!! Thank you!

**Comment by alexbell62** [comment]
hi @jduvesnu could you share your config, please? I have the same humidifier and couldnt make it work with this custom component.

**Comment by jduvesnu** [comment]
fan:
   - platform: xiaomi_miio_airpurifier
     name: Xiaomi Air Humidifier
     host: 192.168.88.214
     token: de1ba2c12f6149922d9b88109f193110
     model: deerma.humidifier.mjjsq

**Comment by jduvesnu** [comment]
- platform: template
    sensors:
        airpurifier_temperature:
          friendly_name: Air Purifier Temperature
          value_template: '{{ states.fan.xiaomi_air_humidifier.attributes.temperature | float + 1.5 }}'
          unit_of_measurement: '°C'
       
        airpurifier_humidity:
          friendly_name: Air Purifier Humidity
          value_template: '{{ states.fan.xiaomi_air_humidifier.attributes.humidity }}'
          unit_of_measurement: '%'

**Comment by alexbell62** [comment]
thanks!
Is the host and token are of the aqara hub?? I mean they are not for humidifier specifically?

**Comment by jduvesnu** [comment]
I received the token from the mi home application

**Comment by syssi** [comment]
Every miIO device has an individual token. Don't reuse the token of another device. This cannot work.

**Comment by alexbell62** [comment]
hi @syssi 
yeah i got device specific token now, then i got error:
```Error: Platform error fan.xiaomi_miio_airpurifier - cannot import name 'FanMiot' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/init.py)```

Which i solved by adding xiaomi_miio into custom component folder as you adviced [here](https://github.com/syssi/xiaomi_airpurifier/issues/98#issuecomment-733834983).

Now im getting this error:
WHat is the best course of action to fix this one please?
```Logger: custom_components.xiaomi_miio_airpurifier.fan
Source: custom_components/xiaomi_miio_airpurifier/fan.py:1512
Integration: xiaomi_miio_airpurifier (documentation, issues)
First occurred: 17:35:52 (13 occurrences)
Last logged: 17:41:58

Got exception while fetching the state: {'code': -9999, 'message': 'user ack timeout'}```

**Comment by alexbell62** [comment]
The humidifier is now shows up but is unavailable.

**Comment by Wampukas** [comment]
Yep, the same for me.

**Comment by alexbell62** [comment]
I fixed that by removing model from config
