### ISSUE TITLE
Error while setting up platform xiaomi_miio_airpurifier

### ISSUE THREAD

**Issue by baizan1** [syssi/xiaomi_airpurifier#46]
I have this error:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 605, in async_setup_platform
    from miio import AirHumidifierMjjsq
ImportError: cannot import name 'AirHumidifierMjjsq' from 'miio' (/usr/local/lib/python3.7/site-packages/miio/__init__.py)

My config:

fan:
  - platform: xiaomi_miio_airpurifier
    name: Humidificador_habitacion
    model: deerma.humidifier.mjjsq
    host: !secret humidifier_hostname
    token: !secret humidifier_token

Only ocurrs when there are sensors declared like this:

  - platform: template
    sensors:
      alerta_deposito_humidificador:
        friendly_name: Air Humidifier alerta deposito
        value_template: '{{ states.fan.humidificador_habitacion.attributes.water_tank_detached }}'

Is it possible to add more time to import miio?

**Comment by syssi** [comment]
Please update the custom component and try again!
