### ISSUE TITLE
deerma.humidifier.mjjsq no water not updated

### ISSUE THREAD

**Issue by Frix-x** [syssi/xiaomi_airpurifier#57]
Hello,

I've got my deerma humidifer working almost perfect with HomeAssistant using your integration. Thank you for the work you've done !

I've still a little problem : when there is no more water inside the tank, the humidifier shut down automaticaly and I got a notification from the MiHome app on my phone. But, in HomeAssistant, the attribute "no water" is not updated to "true". I would like to use this property to add some automation with TTS and so on but at this time I can't as it's not updating as expected.

To analyze deeper : if I start it again manualy (using either the button or HA), it will start and work for approximately 30s, then shutdown again and this time the attribute get updated.

Is this a bug ? Maybe this property is polled on start up and regularly during the runtime of the device but should be polled one more time after the shutdown of the humidifier in your integration ?

Thank you for your help !

**Comment by syssi** [comment]
You could enable the debug output of the underlying library by:

```
logger:
  default: warn
  logs:
    custom_components.sensor.xiaomi_miio_raw: info
    miio: debug
```

You should see the result of the polling now. The HA component calls `get_prop` periodically to retrieve the `no_water`. Does this value change if there is no water? I assume it's a firmware bug.

**Comment by Frix-x** [comment]
Ok, I've enabled the debug logs and here what I've got when the humidifer shutdown automaticaly (when there is no more water):

(1) is before the shutdown, there is still water in the tank
(2) is just after when there is no more water

![image](https://user-images.githubusercontent.com/10575621/81287107-7e658a80-9062-11ea-8a5d-fe17420856f3.png)

As you can see, the water status is correctly retrieved from miio at this time.
However I saw something quite strange: the `waterstatus` come back to `1` on the next loop ! So I assume that this parameter is a one time "alert" flag and don't know how to manage it correctly in your component...

**Comment by syssi** [comment]
This is hard to manage. It's possible to determine the water tank is filled again?

**Comment by Frix-x** [comment]
Solution on my side that I will try : doing a template sensor based on this attribute.
Then I will add another binary_sensor that will be set to true when the "no_water" attribute is set to true.
Then an automation to set back the binary_sensor to false when I "unplug" the water tank (assuming that I unplug it every time a refill it).

I don't know if this logic should belongs to the custom component or not...

**Comment by Frix-x** [comment]
> This is hard to manage. It's possible to determine the water tank is filled again?

No, not really beside the fact that you can know when the water tank is detached. In my case using this would be fine as I detach it from the base everytime I refill it. However I assume that some people will just prefer to let it on place, open the cover and fill it from a bottle...

**Comment by syssi** [comment]
I will close this issue. Okay?
