### ISSUE TITLE
conflict with roborock?

### ISSUE THREAD

**Issue by junologue** [syssi/xiaomi_airpurifier#59]
Here is my error for my vacuum cleaner,  whenever i have your "Xiaomi Mi Air Purifier and Xiaomi Mi Air Humidifier Integration" installed. current version 0.50

any clues? i guess it has something to do with the name "xiaomi_miio" that my vacuum has

Log Details (ERROR)
Logger: homeassistant.components.vacuum
Source: components/xiaomi_miio/vacuum.py:459 
Integration: Vacuum (documentation, issues) 
First occurred: May 10, 2020, 8:53:50 PM (1 occurrences) 
Last logged: May 10, 2020, 8:53:50 PM

xiaomi_miio: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 322, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/vacuum.py", line 459, in update
    self._fan_speeds = self._vacuum.fan_speed_presets()
AttributeError: 'Vacuum' object has no attribute 'fan_speed_presets'

**Comment by syssi** [comment]
Please update the custom component and try again.

**Comment by junologue** [comment]
Just did, even when i uninstall it through hacs it still doesnt work... tried uninstall and reinstall, several times. rebooted hassio etc. hmm, very weird.. any clues?

**Comment by syssi** [comment]
Could you provide a list of custom components you are using?

**Comment by junologue** [comment]
I found a solution, wrong version of 'required' python-miio in xiaomi_miio_airpurifier, inside manifest.json

found clues here:
https://github.com/home-assistant/core/issues/34955

Thank you for your time!
