### ISSUE TITLE
Add support for zhimi.fan.za3

### ISSUE THREAD

**Issue by strutings** [syssi/xiaomi_airpurifier#64]
zhimi.fan.za3 2.0.3 esp32 detected
ERROR (MainThread) [homeassistant.components.xiaomi_miio.fan] Unsupported device found! Please create an issue at https://github.com/syssi/xiaomi_airpurifier/issues and provide the following data: zhimi.fan.za3

**Comment by syssi** [comment]
Please the custom component. The devices is supported now.
