### ISSUE TITLE
UI: Change the color of the icon if the device is active

### ISSUE THREAD

**Issue by syssi** [syssi/xiaomi_airpurifier#8]
https://github.com/home-assistant/home-assistant-polymer/blob/master/src/components/entity/state-badge.html#L24 needs to be extended for the device class fan. 

Suggested by https://github.com/syssi/xiaomi_airpurifier/issues/3#issuecomment-331691133

**Comment by bachulator** [comment]
I wonder is "fan" class extension is the reason I can't set scene for the purifier as well?

**Comment by syssi** [comment]
I don't know. I must admit I didn't used scenes right now.

**Comment by bachulator** [comment]
Ok, lets see if the icon issue will be resolved, perhaps it will resolve the scene issue as well.

**Comment by syssi** [comment]
Will be solved with: https://github.com/home-assistant/home-assistant-polymer/pull/437

**Comment by syssi** [comment]
The feature was merged and will be part of the next release of Home Assistant.

**Comment by bachulator** [comment]
0.55 doesn't bring the functionality

**Comment by syssi** [comment]
![fan](https://user-images.githubusercontent.com/2735933/31375083-ab0716e6-ada0-11e7-90ac-a2b948308a59.png) ;-)

**Comment by bachulator** [comment]
Yes, it works :) Due to changes to 0.55 (the recoder one) the UI didn' t update the icon, but when I have solved the issue with recorder it work perfectly. Thanks, great work there.
