### ISSUE TITLE
SmartMi Evaporative Humidifier

### ISSUE THREAD

**Issue by dudyn5ky1** [syssi/xiaomi_airpurifier#80]
Hello, 

Can't find **SmartMi Evaporative Humidifier** on the list of supported devices. Is it supported? Or are there any plans to add support for it in the near future?

Thanks a lot

**Comment by syssi** [comment]
Do you know the model name of the device?

**Comment by dudyn5ky1** [comment]
@syssi CJXJSQ02ZM

**Comment by syssi** [comment]
@lenisko You own a SmartMi Evaporative Humidifier (CJXJSQ02ZM), correct? Could you tell me the model name of your device? It should be something like `zhimi.humidifier.ca1` or `zhimi.humidifier.cb1` etc. Thanks in advance!

**Comment by syssi** [comment]
I'm trying to build a list of supported devices: https://github.com/syssi/xiaomi_airpurifier#supported-devices

**Comment by lenisko** [comment]
@syssi Hey! I will share it as soon as I will take him out of the basement, leaving myself a note 👍

**Comment by robi59italy** [comment]
I have the model CJXJSQ02ZM (according to the Xiaomi instruction) and it's recognized with zhimi.humidifier.cb1

Official name: Xiaomi Smartmi Evaporative Humidifier (europe version)

**Comment by syssi** [comment]
@robi59italy Could you try to use the device with this custom component. This device is already supported. Could you provide some specs about the device? In most cases the specs are part of a label at the bottom of the device. I would like to extend the list of supported devices: 

https://github.com/syssi/xiaomi_airpurifier#supported-devices

**Comment by robi59italy** [comment]
Sebastian
I can send you same pictures but I need an email address. tried to answer directly to yr message but it didn't work.

**Comment by syssi** [comment]
@robi59italy basti@linkt.de
