### ISSUE TITLE
Supported Device

### ISSUE THREAD

**Issue by robyevolution** [syssi/xiaomi_airpurifier#81]
Hello are this device supported?

https://aliexpress.ru/item/1005001555956596.html?spm=a2g0o.cart.0.0.19493c00rrD3kl&mp=1

and

https://aliexpress.ru/item/1005001356457727.html?spm=a2g0o.cart.0.0.19493c00rrD3kl&mp=1

**Comment by 4ertik131** [comment]
Hey . on the first link supports exactly. I'm setting it up myself now. here is a good link on setup
https://mysku.ru/blog/aliexpress/80395.html

**Comment by syssi** [comment]
@4ertik131 The first one is an `deerma.humidifier.mjjsq`, correct?

**Comment by 4ertik131** [comment]
> @4ertik131 The first one is an `deerma.humidifier.mjjsq`, correct?

Yes that's right .

deerma.humidifier.mjjsq - 40w power

deerma.humidifier.jsq1 - 25w power

**Comment by syssi** [comment]
@4ertik131 Could you provide the model numbers and product names of these devices? I'm trying to improve this list: https://github.com/syssi/xiaomi_airpurifier/#supported-devices

**Comment by 4ertik131** [comment]
deerma.humidifier.mjjsq
![IMG_20201101_004808](https://user-images.githubusercontent.com/73563169/97790728-17bdc580-1bdc-11eb-9c31-612cc834ef59.jpg)

**Comment by 4ertik131** [comment]
Xiaomi Mi Smart Sterilization Humidifier S 
deerma.humidifier.mjjsq
![IMG_20201101_004808](https://user-images.githubusercontent.com/73563169/97796987-ccca9f00-1c29-11eb-8a85-5b56737745a2.jpg)


Xiaomi Mijia Intelligent Sterilization Humidifier SCK0A45
deerma.humidifier.jsq1
![IMG_20201101_095517](https://user-images.githubusercontent.com/73563169/97797006-10250d80-1c2a-11eb-8b2b-8433788c7aac.jpg)

**Comment by syssi** [comment]
Thanks! I would interpret the model no. as SCKOA45 (O vs. 0).
