### ISSUE TITLE
Not a valid add-on repository

### ISSUE THREAD

**Issue by 4ertik131** [syssi/xiaomi_airpurifier#83]
![Screenshot_2020-10-28-15-56-11-878_com android chrome](https://user-images.githubusercontent.com/73563169/97438751-49adfe00-1936-11eb-8ff7-ab563fe92a1a.jpg)
Hello, when I try to add a custom component, I get an error ,, Not a valid add-on repository ,,
tell me what is the reason?

**Comment by syssi** [comment]
This isn't and cannot be a "hass.io add-on". Please use HACS to add the repository and install this *custom component*.
