### ISSUE TITLE
Xiaomi Air Purifier 2H cannot selected (zhimi.airpurifier.mc2)

### ISSUE THREAD

**Issue by ezzq** [syssi/xiaomi_airpurifier#84]
I cannot select the Air Purifier 2H.
When i check the Configuration in the Server Settings befor restart HA:

Invalid config for [fan.xiaomi_miio_airpurifier]: value is not allowed for dictionary value @ data['model']. Got 'zhimi.airpurifier.mc2'. (See ?, line ?).

Configuration.yaml:
fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Air Purifier
    host: ###hidden###
    token: ###hidden###
    model: zhimi.airpurifier.mc2

HA Version 0.117.0
AddOn-Version 0.5 (latest Version i think)

**Comment by syssi** [comment]
How did you install the custom component?

**Comment by ezzq** [comment]
I installed it with the HACS.
Just installed your super new Version 0.6 and now the Config check works. My Air Purifier is still unavailable but i think that is an issue with my token.

Thanks for your super fast reply!!

**Comment by syssi** [comment]
Do you aware of the Xiaomi cloud clients to retrieve the token?

**Comment by ezzq** [comment]
Yes, i use the old MiHome APK and the Custom Integration "Xiaomi Gateway 3" (https://github.com/AlexxIT/XiaomiGateway3).
This also works for me perfect with my Vacuum but not with my Air Purifier...

**Comment by syssi** [comment]
I'm talking about this tool: https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor

It can be used to retrieve the miIO tokens from the Xiaomi Cloud.

**Comment by ezzq** [comment]
This Tool is new for me but shows the same token as the other Apps.
I have also enabled the debugging for the fan section and there is only an timeout for the Custom Component: fan.xiaomi_miio_airpurifier

**Comment by syssi** [comment]
Is the IP address of the device correct, too?

**Comment by syssi** [comment]
Is the device and Home Assistant in the same subnet? No VLANs involved?

**Comment by ezzq** [comment]
The Problem is solved. I moved the Purifier to the HA Subnet. It is a bit stupid that the Roborock with the same rules worked on the other Network.

Thanks for your time and help!

**Comment by syssi** [comment]
The Roborock is a full-featured linux host / ip-stack. The humidifier is esp32 or esp8266 based. This uC is very limited.
