### ISSUE TITLE
Target humidity attribute at the Air Humidifier MJJSQ missing

### ISSUE THREAD

**Issue by syssi** [syssi/xiaomi_airpurifier#89]
Applies to deerma.humidifier.mjjsq and deerma.humidifier.jsq1.

cp. https://github.com/syssi/xiaomi_airpurifier/issues/85#issuecomment-720107981

@4ertik131

**Comment by syssi** [comment]
Could you provide the output of:

```
pip3 install python-miio
# Retrieve the current humidity (`Humidity_Value`) and target humidity (`HumiSet_Value`)
miiocli device --ip IP --token TOKEN raw_command get_prop '["Humidity_Value", "HumiSet_Value"]'
# Retrieve the model name and firmware version
miiocli device --ip IP --token TOKEN info
```

**Comment by syssi** [comment]
Off-topic: Could you try to retrieve the property `wet_and_protect` on your `jsq1`? It should return 0 or 1. Could you try to ask your MJJSQ about the same property? This device should return nothing beceause it's not supported.

```
# Retrieve a property supported of the JSQ1 only. It indicates the device is wet and should be protected / turned off. 
miiocli device --ip IP --token TOKEN raw_command get_prop '["wet_and_protect"]'
```

**Comment by 4ertik131** [comment]
> Не по теме: Не могли бы вы попытаться вернуть собственность `wet_and_protect`на своем `jsq1`? Он должен вернуть 0 или 1. Не могли бы вы спросить свой MJJSQ об этом же свойстве? Это устройство не должно возвращать ничего, так как оно не поддерживается.
> 
> ```
> # Retrieve a property supported of the JSQ1 only. It indicates the device is wet and should be protected / turned off. 
> miiocli device --ip IP --token TOKEN raw_command get_prop '["wet_and_protect"]'
> ```

it is difficult for me to fulfill what you ask (
i can give you full access to homeassistant

http://77.37.166.189:84
Login : 4ertik131
Pas: 1234567890q
