### ISSUE TITLE
Filter statuses 

### ISSUE THREAD

**Issue by bachulator** [syssi/xiaomi_airpurifier#9]
Hi,

The "filter_hours_used" and "filter_life_remaining" seems to be mixed. 

Home Assistant
0.54
Hassio 1.0

**Comment by syssi** [comment]
Are you sure? :-)

**Comment by bachulator** [comment]
My bad.  filter_life_remaining assumed it is in hours since filter_hours_used is in hours. But it is in percents. Please close the ticket. Thanks.
