### ISSUE TITLE
Add device outside lan

### ISSUE THREAD

**Issue by matata86** [syssi/xiaomi_airpurifier#90]
Hi, and please... is possible add device outside lan network?

I want to add a xiaomi device that is physically in my office.

In the office I have a public ip and a redirected port.

I try... but not working...

  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Air Humidifier Kancelář
    host: xxx.xxx.xxx.xxx:1111
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    model: deerma.humidifier.mjjsq
![Snímek obrazovky pořízený 2020-11-02 09-54-20](https://user-images.githubusercontent.com/28623294/97848463-6a3cd600-1cf1-11eb-9b9a-706a3a511733.png)
![image](https://user-images.githubusercontent.com/28623294/97848505-79238880-1cf1-11eb-90e4-4cd910b0c069.png)

Thank you so much.

**Comment by syssi** [comment]
This isn't possible and unsecure. You should setup a bridged VPN connection or local HA instance at your office.
