### ISSUE TITLE
Add zhimi.airpurifier.mc2 support

### ISSUE THREAD

**Issue by ciganskovic** [syssi/xiaomi_airpurifier#91]
I bought the Xiaomi Air Purifier 2H but unfortunately there's no support to add it to Home Assistant yet.
I see that the device zhimi.airpurifier.mc2 is defined in the code but when i define the model in the configuration.yaml i get

`
Invalid config for [fan.xiaomi_miio]: value is not allowed for dictionary value @ data['model']. Got 'zhimi.airpurifier.mc2'. (See ?, line ?). 
`

**Comment by syssi** [comment]
Are you able to install `python-miio` and make some `miiocli` calls to provide some responses of your device?

**Comment by ciganskovic** [comment]
sure miiocli is installed. Just let me know what to run.

**Comment by ciganskovic** [comment]
i already tested it by myself now and found out that i took the wrong token.

**Comment by syssi** [comment]
Why did you close the issue? Does the custom component work for you? If yes, I would like to add the device to the list of supported devices.

**Comment by syssi** [comment]
Could you provide the model no. of your device too? I'm trying to improve this list of supported devices: 

https://github.com/syssi/xiaomi_airpurifier#supported-devices

**Comment by ciganskovic** [comment]
The custom component does work for me. The model number is
zhimi.airpurifier.mc2. Let me know if you need more information.

**Comment by syssi** [comment]
@ciganskovic Could you check the label on the purifier. I'm looking for `FJY4026GL` or something else.

**Comment by ciganskovic** [comment]
@syssi Model Nr. is `AC-M9-AA`
