### ISSUE TITLE
Add wet protection of the deerma.humidifier.jsq1

### ISSUE THREAD

**Issue by 4ertik131** [syssi/xiaomi_airpurifier#92]
![IMG_20201105_130154](https://user-images.githubusercontent.com/73563169/98226532-34a12280-1f67-11eb-83c0-08cb942930d9.jpg)

there is such a function on humidifiers ,, over wet protection ,, 

The smart humidifier knows what to do.
Does not create conditions for the development of bacteria
The MiHome smart humidifier has a new anti-moisture function. While operating at the third speed, it constantly monitors the air humidity and if it exceeds 70% for 1 hour, it automatically switches to the first speed to avoid excessive humidification of the air, which creates conditions for the development of bacteria and the appearance of sediment on surfaces.

The protection function works only at 3 speeds, the function is on by default, you can turn it off via the MiHome app.

**Comment by syssi** [comment]
The `deerma.humidifier.mjjsq` doesn't support this feature, right?

**Comment by syssi** [comment]
```
Method:

Set_wet_and_protect [1] # on
Set_wet_and_protect [0] # off

Property:

wet_and_protect
```

**Comment by 4ertik131** [comment]
> `deerma.humidifier.mjjsq`Не поддерживает эту функцию, не так ли?


only deerma.humidifier.mjjsq has this function
![Screenshot_2020-11-05-16-50-17-600_com xiaomi smarthome](https://user-images.githubusercontent.com/73563169/98252612-32e95600-1f8b-11eb-9021-861eb28b6477.jpg)



> `deerma.humidifier.mjjsq`Не поддерживает эту функцию, не так ли?

**Comment by syssi** [comment]
This is the base for the feature: https://github.com/rytilahti/python-miio/pull/856

**Comment by syssi** [comment]
Are you sure you don't mix up devices here? I cannot find the feature at the native react android app of the MJJSQ.

**Comment by 4ertik131** [comment]
> Вы уверены, что здесь не перепутали устройства? Я не могу найти эту функцию в приложении Android для Android MJJSQ.

100% only deerma.humidifier.mjjsq has this function. 

Please note that this option appears only in the third mode of operation!

**Comment by syssi** [comment]
This is the cause why I'm not believe this:

```
$ grep -ri "Change to low if RH" deerma.humidifier.jsq1
deerma.humidifier.jsq1/android/temp.bundle:      Wet_and_protect_tips: 'Change to low if RH>70% for 1 h',
deerma.humidifier.jsq1/android/main.bundle:      Wet_and_protect_tips: 'Change to low if RH>70% for 1 h',
$
$ grep -ri "Change to low if RH" deerma.humidifier.mjjsq 
$ # no hits
```

**Comment by syssi** [comment]
Could you try to install `python-miio´ and make some `miiocli` calls?

**Comment by syssi** [comment]
```
# Retrieve a property supported of the JSQ1 only. It indicates the device is wet and should be protected / turned off. 
miiocli device --ip IP --token TOKEN raw_command get_prop '["wet_and_protect"]'
```

**Comment by 4ertik131** [comment]
> Не могли бы вы попробовать установить `python-miio`и сделать несколько `miiocli`звонков?

I have installed

what commands to enter for

> Не могли бы вы попробовать установить `python-miio`и сделать несколько `miiocli`звонков?

I have installed `python-miio`

what commands to enter for `miiocli`?

**Comment by syssi** [comment]
```
# two requests for the MJJSQ
miiocli device --ip IP1 --token TOKEN1 raw_command get_prop '["wet_and_protect"]'
miiocli device --ip IP1 --token TOKEN1 

# two requests for the JSQ1
miiocli device --ip IP2 --token TOKEN2 raw_command get_prop '["wet_and_protect"]'
miiocli device --ip IP2 --token TOKEN2 
```

**Comment by 4ertik131** [comment]
> ```
> # two requests for the MJJSQ
> miiocli device --ip IP1 --token TOKEN1 raw_command get_prop '["wet_and_protect"]'
> miiocli device --ip IP1 --token TOKEN1 
> 
> # two requests for the JSQ1
> miiocli device --ip IP2 --token TOKEN2 raw_command get_prop '["wet_and_protect"]'
> miiocli device --ip IP2 --token TOKEN2 
> ```
it might be harder than usual.

![IMG_20201105_184614](https://user-images.githubusercontent.com/73563169/98263081-6d58f000-1f97-11eb-9ddf-bfef59b3e51d.jpg)


can we check another way? add this option to custom component to the develop branch. and i will check

**Comment by syssi** [comment]
Lol. Please replace IP1 with the IP address of your MJJSQ and TOKEN1 with the token of your device. Same applies to TOKEN2 and IP2.

**Comment by 4ertik131** [comment]
> Лол. Пожалуйста, замените IP1 на IP-адрес вашего MJJSQ и TOKEN1 на токен вашего устройства. То же самое относится к TOKEN2 и IP2.

![Screenshot_2020-11-05-19-23-31-876_com xiaomi smarthome](https://user-images.githubusercontent.com/73563169/98267451-76988b80-1f9c-11eb-8215-11fb01f3e97d.jpg)
I understood what you want to check. I have not specified only one device in my network and I cannot confuse them.

**Comment by syssi** [comment]
I need the response of both commands nevertheless. My be the property of the MJJSQ has another name. I would be cool if you could provide the responses to get a better understanding of the devices.

**Comment by 4ertik131** [comment]
> Тем не менее мне нужен ответ обеих команд. Может быть свойство MJJSQ имеет другое название. Было бы здорово, если бы вы могли предоставить ответы, чтобы лучше понять устройства.

![IMG_20201105_193321](https://user-images.githubusercontent.com/73563169/98268758-f8d57f80-1f9d-11eb-8323-000ca4704572.jpg)

**Comment by 4ertik131** [comment]
> Тем не менее мне нужен ответ обеих команд. Может быть свойство MJJSQ имеет другое название. Было бы здорово, если бы вы могли предоставить ответы, чтобы лучше понять устройства.

![IMG_20201105_193321](https://user-images.githubusercontent.com/73563169/98268849-11459a00-1f9e-11eb-84ff-759be263b594.jpg)

**Comment by 4ertik131** [comment]
> Тем не менее мне нужен ответ обеих команд. Может быть свойство MJJSQ имеет другое название. Было бы здорово, если бы вы могли предоставить ответы, чтобы лучше понять устройства.

miiocli device --ip IP1 --token TOKEN1 info :1st_place_medal: )))))

![IMG_20201105_200155](https://user-images.githubusercontent.com/73563169/98272493-33d9b200-1fa2-11eb-9507-c95151674377.jpg)

**Comment by syssi** [comment]
I made a mistake at the second command. It must be:

```
miiocli device --ip IP1 --token TOKEN1 raw_command get_prop '["wet_and_protect"]'
miiocli device --ip IP1 --token TOKEN1 info
```

**Comment by syssi** [comment]
Alright. The JSQ1 supports the `wet_and_protect` property. What about the MJJSQ?

**Comment by 4ertik131** [comment]
> Хорошо. JSQ1 поддерживает это `wet_and_protect`свойство. А как насчет MJJSQ?

on my network now only MJJSQ

![IMG_20201105_201017](https://user-images.githubusercontent.com/73563169/98273571-7a7bdc00-1fa3-11eb-8f87-a8dc6c41e2c8.jpg)

**Comment by syssi** [comment]
May be the list of supported devices is wrong and it must look like this:

| Name                   | Model                  | Model no. | Specs |
| ---------------------- | ---------------------- | --------- | ----- |
| Mijia Smart Sterilization Humidifier S  | deerma.humidifier.mjjsq  | SCKOA45, SCK0A45  | 4.5L, <=39dB, 450mL/h, 40W  |
| Mijia Intelligent Sterilization Humidifier SCK0A45  | deerma.humidifier.jsq1    | MJJSQ03DY  | 4.5L, <=38dB, 300mL/h, 25W |

What do you think?

**Comment by 4ertik131** [comment]
@syssi 
I think they are Chinese! made two models on one board, and the difference is in the evaporator power and firmware.

here are screenshots of mixome SCK0A45
![IMG-20201105-WA0024](https://user-images.githubusercontent.com/73563169/98276843-a00ae480-1fa7-11eb-833c-b5dbc17ee80c.jpg)
![IMG-20201105-WA0021](https://user-images.githubusercontent.com/73563169/98276848-a13c1180-1fa7-11eb-8455-a9e30ce6e1bf.jpg)

here are screenshots of mixome MJJSQ03DY
![Screenshot_2020-11-05-20-49-44-823_com xiaomi smarthome](https://user-images.githubusercontent.com/73563169/98277476-7ef6c380-1fa8-11eb-927e-b831bd130710.jpg)
![Screenshot_2020-11-05-20-49-14-280_com xiaomi smarthome](https://user-images.githubusercontent.com/73563169/98277480-8027f080-1fa8-11eb-9775-b5442d466c24.jpg)

**Comment by 4ertik131** [comment]
@syssi  
I tested two configs on mine, both work fine !!!!
'''
fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Air Humidifier
    host: 192.168.1.191
    token: e23dfbcf44f8aeea9e82d409c9c21e2b
    model: deerma.humidifier.mjjsq
'''
'''
fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Air Humidifier
    host: 192.168.1.191
    token: e23dfbcf44f8aeea9e82d409c9c21e2b
    model: deerma.humidifier.jsq1
'''

**Comment by syssi** [comment]
Yes. The only difference between the two devices is the `wet_and_protect` attribute we are talking about.

**Comment by 4ertik131** [comment]
> Да. Единственное различие между двумя устройствами - это `wet_and_protect`атрибут, о котором мы говорим.

add this option to custom component to the develop branch. and i will check

**Comment by 4ertik131** [comment]
> Yes. The only difference between the two devices is the `wet_and_protect` attribute we are talking about.

add this option to custom component to the develop branch. and i will check

**Comment by syssi** [comment]
A release of `python-miio` is required first.

**Comment by 4ertik131** [comment]
@syssi 
![IMG_20201116_164909](https://user-images.githubusercontent.com/73563169/99260065-f986d500-282b-11eb-9892-e62aa30058a4.jpg)
    
good evening !
it took me a while to upgrade to a new python version.

i created a switch wet_protection one ok doesn't work! does not switch state.

 ```  
xiaomi_airpurifier_wet_protection:
        friendly_name: "wet_protection"
        value_template: "{{ is_state_attr('fan.xiaomi_air_humidifier', 'wet_protection', true) }}"
        turn_on:
          service: xiaomi_miio_airpurifier.fan_set_wet_protection_on
          data:
            entity_id: fan.xiaomi_air_humidifier
        turn_off:
          service: xiaomi_miio_airpurifier.fan_set_wet_protection_off
          data:
            entity_id: fan.xiaomi_air_humidifier
        icon_template: "mdi:lightbulb-outline"

```

Am I wrong in the code?
